#
# Module manifest for module 'Microsoft.Graph.Sites'
#
# Generated by: Microsoft Corporation
#
# Generated on: 11/20/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Sites.psm1'

# Version number of this module.
ModuleVersion = '2.25.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '7ae8c25b-f1dd-466d-a022-b5489f919c70'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.25.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Sites.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Sites.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgSite', 'Add-MgSiteContentTypeCopy', 
               'Add-MgSiteContentTypeCopyFromContentTypeHub', 
               'Add-MgSiteListContentTypeCopy', 
               'Add-MgSiteListContentTypeCopyFromContentTypeHub', 
               'Copy-MgSiteContentTypeToDefaultContentLocation', 
               'Copy-MgSiteListContentTypeToDefaultContentLocation', 
               'Copy-MgSiteOnenoteNotebook', 
               'Copy-MgSiteOnenoteNotebookSectionGroupSectionPageToSection', 
               'Copy-MgSiteOnenoteNotebookSectionGroupSectionToNotebook', 
               'Copy-MgSiteOnenoteNotebookSectionGroupSectionToSectionGroup', 
               'Copy-MgSiteOnenoteNotebookSectionPageToSection', 
               'Copy-MgSiteOnenoteNotebookSectionToNotebook', 
               'Copy-MgSiteOnenoteNotebookSectionToSectionGroup', 
               'Copy-MgSiteOnenotePageToSection', 
               'Copy-MgSiteOnenoteSectionGroupSectionPageToSection', 
               'Copy-MgSiteOnenoteSectionGroupSectionToNotebook', 
               'Copy-MgSiteOnenoteSectionGroupSectionToSectionGroup', 
               'Copy-MgSiteOnenoteSectionPageToSection', 
               'Copy-MgSiteOnenoteSectionToNotebook', 
               'Copy-MgSiteOnenoteSectionToSectionGroup', 'Get-MgAdminSharepoint', 
               'Get-MgAdminSharepointSetting', 'Get-MgAllSite', 'Get-MgGroupSite', 
               'Get-MgGroupSiteAnalytic', 
               'Get-MgGroupSiteAnalyticItemActivityStat', 
               'Get-MgGroupSiteAnalyticItemActivityStatActivity', 
               'Get-MgGroupSiteAnalyticItemActivityStatActivityCount', 
               'Get-MgGroupSiteAnalyticItemActivityStatActivityDriveItem', 
               'Get-MgGroupSiteAnalyticItemActivityStatActivityDriveItemContent', 
               'Get-MgGroupSiteAnalyticItemActivityStatCount', 
               'Get-MgGroupSiteAnalyticLastSevenDay', 
               'Get-MgGroupSiteAnalyticTime', 'Get-MgGroupSiteColumn', 
               'Get-MgGroupSiteColumnCount', 'Get-MgGroupSiteColumnSourceColumn', 
               'Get-MgGroupSiteContentType', 'Get-MgGroupSiteContentTypeBase', 
               'Get-MgGroupSiteContentTypeBaseType', 
               'Get-MgGroupSiteContentTypeBaseTypeCount', 
               'Get-MgGroupSiteContentTypeColumn', 
               'Get-MgGroupSiteContentTypeColumnCount', 
               'Get-MgGroupSiteContentTypeColumnLink', 
               'Get-MgGroupSiteContentTypeColumnLinkCount', 
               'Get-MgGroupSiteContentTypeColumnPosition', 
               'Get-MgGroupSiteContentTypeColumnPositionCount', 
               'Get-MgGroupSiteContentTypeColumnSourceColumn', 
               'Get-MgGroupSiteContentTypeCount', 'Get-MgGroupSiteCount', 
               'Get-MgGroupSiteCreatedByUser', 
               'Get-MgGroupSiteCreatedByUserMailboxSetting', 
               'Get-MgGroupSiteCreatedByUserServiceProvisioningError', 
               'Get-MgGroupSiteCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgGroupSiteDefaultDrive', 'Get-MgGroupSiteDrive', 
               'Get-MgGroupSiteDriveCount', 'Get-MgGroupSiteExternalColumn', 
               'Get-MgGroupSiteExternalColumnCount', 'Get-MgGroupSiteGetByPath', 
               'Get-MgGroupSiteGetByPathAnalytic', 
               'Get-MgGroupSiteGetByPathColumn', 
               'Get-MgGroupSiteGetByPathContentType', 
               'Get-MgGroupSiteGetByPathDrive', 
               'Get-MgGroupSiteGetByPathExternalColumn', 
               'Get-MgGroupSiteGetByPathItem', 'Get-MgGroupSiteGetByPathOnenote', 
               'Get-MgGroupSiteGetByPathOperation', 'Get-MgGroupSiteGetByPathPage', 
               'Get-MgGroupSiteGetByPathPermission', 
               'Get-MgGroupSiteGetByPathSite', 'Get-MgGroupSiteGetByPathTermStore', 
               'Get-MgGroupSiteGetGraphBPrePathCreatedByUser', 
               'Get-MgGroupSiteGetGraphBPrePathLastModifiedByUser', 
               'Get-MgGroupSiteItem', 'Get-MgGroupSiteItemCount', 
               'Get-MgGroupSiteItemLastModifiedByUser', 
               'Get-MgGroupSiteItemLastModifiedByUserMailboxSetting', 
               'Get-MgGroupSiteItemLastModifiedByUserServiceProvisioningError', 
               'Get-MgGroupSiteItemLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgGroupSiteLastModifiedByUser', 
               'Get-MgGroupSiteLastModifiedByUserMailboxSetting', 
               'Get-MgGroupSiteLastModifiedByUserServiceProvisioningError', 
               'Get-MgGroupSiteLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgGroupSiteList', 'Get-MgGroupSiteListColumn', 
               'Get-MgGroupSiteListColumnCount', 
               'Get-MgGroupSiteListColumnSourceColumn', 
               'Get-MgGroupSiteListContentType', 
               'Get-MgGroupSiteListContentTypeColumn', 
               'Get-MgGroupSiteListContentTypeColumnCount', 
               'Get-MgGroupSiteListContentTypeColumnLink', 
               'Get-MgGroupSiteListContentTypeColumnLinkCount', 
               'Get-MgGroupSiteListContentTypeColumnPosition', 
               'Get-MgGroupSiteListContentTypeColumnPositionCount', 
               'Get-MgGroupSiteListContentTypeColumnSourceColumn', 
               'Get-MgGroupSiteListContentTypeCount', 'Get-MgGroupSiteListCount', 
               'Get-MgGroupSiteListCreatedByUser', 
               'Get-MgGroupSiteListCreatedByUserMailboxSetting', 
               'Get-MgGroupSiteListCreatedByUserServiceProvisioningError', 
               'Get-MgGroupSiteListCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgGroupSiteListDrive', 'Get-MgGroupSiteListItem', 
               'Get-MgGroupSiteListItemAnalytic', 
               'Get-MgGroupSiteListItemCreatedByUser', 
               'Get-MgGroupSiteListItemCreatedByUserMailboxSetting', 
               'Get-MgGroupSiteListItemCreatedByUserServiceProvisioningError', 
               'Get-MgGroupSiteListItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgGroupSiteListItemDocumentSetVersion', 
               'Get-MgGroupSiteListItemDocumentSetVersionCount', 
               'Get-MgGroupSiteListItemDocumentSetVersionField', 
               'Get-MgGroupSiteListItemDriveItem', 
               'Get-MgGroupSiteListItemDriveItemContent', 
               'Get-MgGroupSiteListItemField', 'Get-MgGroupSiteListItemVersion', 
               'Get-MgGroupSiteListItemVersionCount', 
               'Get-MgGroupSiteListItemVersionField', 
               'Get-MgGroupSiteListOperation', 'Get-MgGroupSiteListOperationCount', 
               'Get-MgGroupSiteListSubscription', 
               'Get-MgGroupSiteListSubscriptionCount', 'Get-MgGroupSiteOnenote', 
               'Get-MgGroupSiteOnenoteNotebook', 
               'Get-MgGroupSiteOnenoteNotebookCount', 
               'Get-MgGroupSiteOnenoteNotebookSection', 
               'Get-MgGroupSiteOnenoteNotebookSectionCount', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroup', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroupCount', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroupParentNotebook', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroupParentSectionGroup', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroupSection', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroupSectionCount', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroupSectionPage', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroupSectionPageContent', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroupSectionPageCount', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroupSectionPageParentNotebook', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroupSectionPageParentSection', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroupSectionParentNotebook', 
               'Get-MgGroupSiteOnenoteNotebookSectionGroupSectionParentSectionGroup', 
               'Get-MgGroupSiteOnenoteNotebookSectionPage', 
               'Get-MgGroupSiteOnenoteNotebookSectionPageContent', 
               'Get-MgGroupSiteOnenoteNotebookSectionPageCount', 
               'Get-MgGroupSiteOnenoteNotebookSectionPageParentNotebook', 
               'Get-MgGroupSiteOnenoteNotebookSectionPageParentSection', 
               'Get-MgGroupSiteOnenoteNotebookSectionParentNotebook', 
               'Get-MgGroupSiteOnenoteNotebookSectionParentSectionGroup', 
               'Get-MgGroupSiteOnenoteOperation', 
               'Get-MgGroupSiteOnenoteOperationCount', 
               'Get-MgGroupSiteOnenotePage', 'Get-MgGroupSiteOnenotePageContent', 
               'Get-MgGroupSiteOnenotePageCount', 
               'Get-MgGroupSiteOnenotePageParentNotebook', 
               'Get-MgGroupSiteOnenotePageParentSection', 
               'Get-MgGroupSiteOnenoteResource', 
               'Get-MgGroupSiteOnenoteResourceContent', 
               'Get-MgGroupSiteOnenoteResourceCount', 
               'Get-MgGroupSiteOnenoteSection', 
               'Get-MgGroupSiteOnenoteSectionCount', 
               'Get-MgGroupSiteOnenoteSectionGroup', 
               'Get-MgGroupSiteOnenoteSectionGroupCount', 
               'Get-MgGroupSiteOnenoteSectionGroupParentNotebook', 
               'Get-MgGroupSiteOnenoteSectionGroupParentSectionGroup', 
               'Get-MgGroupSiteOnenoteSectionGroupSection', 
               'Get-MgGroupSiteOnenoteSectionGroupSectionCount', 
               'Get-MgGroupSiteOnenoteSectionGroupSectionPage', 
               'Get-MgGroupSiteOnenoteSectionGroupSectionPageContent', 
               'Get-MgGroupSiteOnenoteSectionGroupSectionPageCount', 
               'Get-MgGroupSiteOnenoteSectionGroupSectionPageParentNotebook', 
               'Get-MgGroupSiteOnenoteSectionGroupSectionPageParentSection', 
               'Get-MgGroupSiteOnenoteSectionGroupSectionParentNotebook', 
               'Get-MgGroupSiteOnenoteSectionGroupSectionParentSectionGroup', 
               'Get-MgGroupSiteOnenoteSectionPage', 
               'Get-MgGroupSiteOnenoteSectionPageContent', 
               'Get-MgGroupSiteOnenoteSectionPageCount', 
               'Get-MgGroupSiteOnenoteSectionPageParentNotebook', 
               'Get-MgGroupSiteOnenoteSectionPageParentSection', 
               'Get-MgGroupSiteOnenoteSectionParentNotebook', 
               'Get-MgGroupSiteOnenoteSectionParentSectionGroup', 
               'Get-MgGroupSiteOperation', 'Get-MgGroupSiteOperationCount', 
               'Get-MgGroupSitePage', 'Get-MgGroupSitePageAsSitePage', 
               'Get-MgGroupSitePageAsSitePageCanvaLayout', 
               'Get-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSection', 
               'Get-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSectionColumn', 
               'Get-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSectionColumnCount', 
               'Get-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSectionColumnWebpart', 
               'Get-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSectionColumnWebpartCount', 
               'Get-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSectionCount', 
               'Get-MgGroupSitePageAsSitePageCanvaLayoutVerticalSection', 
               'Get-MgGroupSitePageAsSitePageCanvaLayoutVerticalSectionWebpart', 
               'Get-MgGroupSitePageAsSitePageCanvaLayoutVerticalSectionWebpartCount', 
               'Get-MgGroupSitePageAsSitePageCreatedByUser', 
               'Get-MgGroupSitePageAsSitePageCreatedByUserMailboxSetting', 
               'Get-MgGroupSitePageAsSitePageCreatedByUserServiceProvisioningError', 
               'Get-MgGroupSitePageAsSitePageCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgGroupSitePageAsSitePageLastModifiedByUser', 
               'Get-MgGroupSitePageAsSitePageLastModifiedByUserMailboxSetting', 
               'Get-MgGroupSitePageAsSitePageLastModifiedByUserServiceProvisioningError', 
               'Get-MgGroupSitePageAsSitePageLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgGroupSitePageAsSitePageWebPart', 
               'Get-MgGroupSitePageAsSitePageWebPartCount', 
               'Get-MgGroupSitePageCount', 'Get-MgGroupSitePageCountAsSitePage', 
               'Get-MgGroupSitePageCreatedByUser', 
               'Get-MgGroupSitePageCreatedByUserMailboxSetting', 
               'Get-MgGroupSitePageCreatedByUserServiceProvisioningError', 
               'Get-MgGroupSitePageCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgGroupSitePageLastModifiedByUser', 
               'Get-MgGroupSitePageLastModifiedByUserMailboxSetting', 
               'Get-MgGroupSitePageLastModifiedByUserServiceProvisioningError', 
               'Get-MgGroupSitePageLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgGroupSitePermission', 'Get-MgGroupSitePermissionCount', 
               'Get-MgGroupSiteTermStore', 'Get-MgGroupSiteTermStoreCount', 
               'Get-MgGroupSiteTermStoreGroup', 
               'Get-MgGroupSiteTermStoreGroupCount', 
               'Get-MgGroupSiteTermStoreGroupSet', 
               'Get-MgGroupSiteTermStoreGroupSetChild', 
               'Get-MgGroupSiteTermStoreGroupSetChildCount', 
               'Get-MgGroupSiteTermStoreGroupSetChildRelation', 
               'Get-MgGroupSiteTermStoreGroupSetChildRelationCount', 
               'Get-MgGroupSiteTermStoreGroupSetChildRelationFromTerm', 
               'Get-MgGroupSiteTermStoreGroupSetChildRelationSet', 
               'Get-MgGroupSiteTermStoreGroupSetChildRelationToTerm', 
               'Get-MgGroupSiteTermStoreGroupSetChildSet', 
               'Get-MgGroupSiteTermStoreGroupSetCount', 
               'Get-MgGroupSiteTermStoreGroupSetParentGroup', 
               'Get-MgGroupSiteTermStoreGroupSetRelation', 
               'Get-MgGroupSiteTermStoreGroupSetRelationCount', 
               'Get-MgGroupSiteTermStoreGroupSetRelationFromTerm', 
               'Get-MgGroupSiteTermStoreGroupSetRelationSet', 
               'Get-MgGroupSiteTermStoreGroupSetRelationToTerm', 
               'Get-MgGroupSiteTermStoreGroupSetTerm', 
               'Get-MgGroupSiteTermStoreGroupSetTermChild', 
               'Get-MgGroupSiteTermStoreGroupSetTermChildCount', 
               'Get-MgGroupSiteTermStoreGroupSetTermChildRelation', 
               'Get-MgGroupSiteTermStoreGroupSetTermChildRelationCount', 
               'Get-MgGroupSiteTermStoreGroupSetTermChildRelationFromTerm', 
               'Get-MgGroupSiteTermStoreGroupSetTermChildRelationSet', 
               'Get-MgGroupSiteTermStoreGroupSetTermChildRelationToTerm', 
               'Get-MgGroupSiteTermStoreGroupSetTermChildSet', 
               'Get-MgGroupSiteTermStoreGroupSetTermCount', 
               'Get-MgGroupSiteTermStoreGroupSetTermRelation', 
               'Get-MgGroupSiteTermStoreGroupSetTermRelationCount', 
               'Get-MgGroupSiteTermStoreGroupSetTermRelationFromTerm', 
               'Get-MgGroupSiteTermStoreGroupSetTermRelationSet', 
               'Get-MgGroupSiteTermStoreGroupSetTermRelationToTerm', 
               'Get-MgGroupSiteTermStoreGroupSetTermSet', 
               'Get-MgGroupSiteTermStoreSet', 'Get-MgGroupSiteTermStoreSetChild', 
               'Get-MgGroupSiteTermStoreSetChildCount', 
               'Get-MgGroupSiteTermStoreSetChildRelation', 
               'Get-MgGroupSiteTermStoreSetChildRelationCount', 
               'Get-MgGroupSiteTermStoreSetChildRelationFromTerm', 
               'Get-MgGroupSiteTermStoreSetChildRelationSet', 
               'Get-MgGroupSiteTermStoreSetChildRelationToTerm', 
               'Get-MgGroupSiteTermStoreSetChildSet', 
               'Get-MgGroupSiteTermStoreSetCount', 
               'Get-MgGroupSiteTermStoreSetParentGroup', 
               'Get-MgGroupSiteTermStoreSetParentGroupSet', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetChild', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetChildCount', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetChildRelation', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetChildRelationCount', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetChildRelationFromTerm', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetChildRelationSet', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetChildRelationToTerm', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetChildSet', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetCount', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetRelation', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetRelationCount', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetRelationFromTerm', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetRelationSet', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetRelationToTerm', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTerm', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermChild', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermChildCount', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermChildRelation', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermChildRelationCount', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermChildRelationFromTerm', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermChildRelationSet', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermChildRelationToTerm', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermChildSet', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermCount', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermRelation', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermRelationCount', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermRelationFromTerm', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermRelationSet', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermRelationToTerm', 
               'Get-MgGroupSiteTermStoreSetParentGroupSetTermSet', 
               'Get-MgGroupSiteTermStoreSetRelation', 
               'Get-MgGroupSiteTermStoreSetRelationCount', 
               'Get-MgGroupSiteTermStoreSetRelationFromTerm', 
               'Get-MgGroupSiteTermStoreSetRelationSet', 
               'Get-MgGroupSiteTermStoreSetRelationToTerm', 
               'Get-MgGroupSiteTermStoreSetTerm', 
               'Get-MgGroupSiteTermStoreSetTermChild', 
               'Get-MgGroupSiteTermStoreSetTermChildCount', 
               'Get-MgGroupSiteTermStoreSetTermChildRelation', 
               'Get-MgGroupSiteTermStoreSetTermChildRelationCount', 
               'Get-MgGroupSiteTermStoreSetTermChildRelationFromTerm', 
               'Get-MgGroupSiteTermStoreSetTermChildRelationSet', 
               'Get-MgGroupSiteTermStoreSetTermChildRelationToTerm', 
               'Get-MgGroupSiteTermStoreSetTermChildSet', 
               'Get-MgGroupSiteTermStoreSetTermCount', 
               'Get-MgGroupSiteTermStoreSetTermRelation', 
               'Get-MgGroupSiteTermStoreSetTermRelationCount', 
               'Get-MgGroupSiteTermStoreSetTermRelationFromTerm', 
               'Get-MgGroupSiteTermStoreSetTermRelationSet', 
               'Get-MgGroupSiteTermStoreSetTermRelationToTerm', 
               'Get-MgGroupSiteTermStoreSetTermSet', 'Get-MgGroupSubSite', 
               'Get-MgGroupSubSiteCount', 'Get-MgSite', 
               'Get-MgSiteActivityByInterval', 'Get-MgSiteAnalytic', 
               'Get-MgSiteAnalyticItemActivityStat', 
               'Get-MgSiteAnalyticItemActivityStatActivity', 
               'Get-MgSiteAnalyticItemActivityStatActivityCount', 
               'Get-MgSiteAnalyticItemActivityStatActivityDriveItem', 
               'Get-MgSiteAnalyticItemActivityStatActivityDriveItemContent', 
               'Get-MgSiteAnalyticItemActivityStatCount', 
               'Get-MgSiteAnalyticLastSevenDay', 'Get-MgSiteAnalyticTime', 
               'Get-MgSiteApplicableContentTypeForList', 'Get-MgSiteByPath', 
               'Get-MgSiteColumn', 'Get-MgSiteColumnCount', 
               'Get-MgSiteColumnSourceColumn', 'Get-MgSiteContentType', 
               'Get-MgSiteContentTypeBase', 'Get-MgSiteContentTypeBaseType', 
               'Get-MgSiteContentTypeBaseTypeCount', 'Get-MgSiteContentTypeColumn', 
               'Get-MgSiteContentTypeColumnCount', 
               'Get-MgSiteContentTypeColumnLink', 
               'Get-MgSiteContentTypeColumnLinkCount', 
               'Get-MgSiteContentTypeColumnPosition', 
               'Get-MgSiteContentTypeColumnPositionCount', 
               'Get-MgSiteContentTypeColumnSourceColumn', 
               'Get-MgSiteContentTypeCompatibleHubContentType', 
               'Get-MgSiteContentTypeCount', 'Get-MgSiteCount', 
               'Get-MgSiteDefaultDrive', 'Get-MgSiteDelta', 'Get-MgSiteDrive', 
               'Get-MgSiteDriveCount', 'Get-MgSiteExternalColumn', 
               'Get-MgSiteExternalColumnCount', 'Get-MgSiteGetByPath', 
               'Get-MgSiteGetByPathAnalytic', 
               'Get-MgSiteGetByPathApplicableContentTypeForList', 
               'Get-MgSiteGetByPathColumn', 'Get-MgSiteGetByPathContentType', 
               'Get-MgSiteGetByPathDrive', 'Get-MgSiteGetByPathExternalColumn', 
               'Get-MgSiteGetByPathOperation', 'Get-MgSiteGetByPathPage', 
               'Get-MgSiteGetByPathPermission', 'Get-MgSiteGetByPathSite', 
               'Get-MgSiteGetByPathTermStore', 
               'Get-MgSiteGetGraphBPrePathActivityByInterval', 
               'Get-MgSiteItemLastModifiedByUser', 
               'Get-MgSiteItemLastModifiedByUserMailboxSetting', 
               'Get-MgSiteItemLastModifiedByUserServiceProvisioningError', 
               'Get-MgSiteItemLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgSiteLastModifiedByUser', 
               'Get-MgSiteLastModifiedByUserMailboxSetting', 
               'Get-MgSiteLastModifiedByUserServiceProvisioningError', 
               'Get-MgSiteLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgSiteList', 'Get-MgSiteListColumn', 'Get-MgSiteListColumnCount', 
               'Get-MgSiteListColumnSourceColumn', 'Get-MgSiteListContentType', 
               'Get-MgSiteListContentTypeColumn', 
               'Get-MgSiteListContentTypeColumnCount', 
               'Get-MgSiteListContentTypeColumnLink', 
               'Get-MgSiteListContentTypeColumnLinkCount', 
               'Get-MgSiteListContentTypeColumnPosition', 
               'Get-MgSiteListContentTypeColumnPositionCount', 
               'Get-MgSiteListContentTypeColumnSourceColumn', 
               'Get-MgSiteListContentTypeCompatibleHubContentType', 
               'Get-MgSiteListContentTypeCount', 'Get-MgSiteListCount', 
               'Get-MgSiteListCreatedByUser', 
               'Get-MgSiteListCreatedByUserMailboxSetting', 
               'Get-MgSiteListCreatedByUserServiceProvisioningError', 
               'Get-MgSiteListCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgSiteListDrive', 'Get-MgSiteListItem', 
               'Get-MgSiteListItemActivityByInterval', 
               'Get-MgSiteListItemAnalytic', 'Get-MgSiteListItemCreatedByUser', 
               'Get-MgSiteListItemCreatedByUserMailboxSetting', 
               'Get-MgSiteListItemCreatedByUserServiceProvisioningError', 
               'Get-MgSiteListItemCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgSiteListItemDelta', 'Get-MgSiteListItemDocumentSetVersion', 
               'Get-MgSiteListItemDocumentSetVersionCount', 
               'Get-MgSiteListItemDocumentSetVersionField', 
               'Get-MgSiteListItemDriveItem', 'Get-MgSiteListItemDriveItemContent', 
               'Get-MgSiteListItemField', 'Get-MgSiteListItemVersion', 
               'Get-MgSiteListItemVersionCount', 'Get-MgSiteListItemVersionField', 
               'Get-MgSiteListOperation', 'Get-MgSiteListOperationCount', 
               'Get-MgSiteListSubscription', 'Get-MgSiteListSubscriptionCount', 
               'Get-MgSiteOnenoteNotebookFromWebUrl', 'Get-MgSiteOperation', 
               'Get-MgSiteOperationCount', 'Get-MgSitePage', 
               'Get-MgSitePageAsSitePage', 'Get-MgSitePageAsSitePageCanvaLayout', 
               'Get-MgSitePageAsSitePageCanvaLayoutHorizontalSection', 
               'Get-MgSitePageAsSitePageCanvaLayoutHorizontalSectionColumn', 
               'Get-MgSitePageAsSitePageCanvaLayoutHorizontalSectionColumnCount', 
               'Get-MgSitePageAsSitePageCanvaLayoutHorizontalSectionColumnWebpart', 
               'Get-MgSitePageAsSitePageCanvaLayoutHorizontalSectionColumnWebpartCount', 
               'Get-MgSitePageAsSitePageCanvaLayoutHorizontalSectionCount', 
               'Get-MgSitePageAsSitePageCanvaLayoutVerticalSection', 
               'Get-MgSitePageAsSitePageCanvaLayoutVerticalSectionWebpart', 
               'Get-MgSitePageAsSitePageCanvaLayoutVerticalSectionWebpartCount', 
               'Get-MgSitePageAsSitePageCreatedByUser', 
               'Get-MgSitePageAsSitePageCreatedByUserMailboxSetting', 
               'Get-MgSitePageAsSitePageCreatedByUserServiceProvisioningError', 
               'Get-MgSitePageAsSitePageCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgSitePageAsSitePageLastModifiedByUser', 
               'Get-MgSitePageAsSitePageLastModifiedByUserMailboxSetting', 
               'Get-MgSitePageAsSitePageLastModifiedByUserServiceProvisioningError', 
               'Get-MgSitePageAsSitePageLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgSitePageAsSitePageWebPart', 
               'Get-MgSitePageAsSitePageWebPartCount', 'Get-MgSitePageCount', 
               'Get-MgSitePageCountAsSitePage', 'Get-MgSitePageCreatedByUser', 
               'Get-MgSitePageCreatedByUserMailboxSetting', 
               'Get-MgSitePageCreatedByUserServiceProvisioningError', 
               'Get-MgSitePageCreatedByUserServiceProvisioningErrorCount', 
               'Get-MgSitePageLastModifiedByUser', 
               'Get-MgSitePageLastModifiedByUserMailboxSetting', 
               'Get-MgSitePageLastModifiedByUserServiceProvisioningError', 
               'Get-MgSitePageLastModifiedByUserServiceProvisioningErrorCount', 
               'Get-MgSitePageMicrosoftGraphSitePageCanvaLayoutHorizontalSectionColumnWebpartPositionOfWebPart', 
               'Get-MgSitePageMicrosoftGraphSitePageCanvaLayoutVerticalSectionWebpartPositionOfWebPart', 
               'Get-MgSitePageMicrosoftGraphSitePageWebPartPositionOfWebPart', 
               'Get-MgSitePermission', 'Get-MgSitePermissionCount', 
               'Get-MgSiteRecentNotebook', 'Get-MgSiteTermStore', 
               'Get-MgSiteTermStoreCount', 'Get-MgSiteTermStoreGroup', 
               'Get-MgSiteTermStoreGroupCount', 'Get-MgSiteTermStoreGroupSet', 
               'Get-MgSiteTermStoreGroupSetChild', 
               'Get-MgSiteTermStoreGroupSetChildCount', 
               'Get-MgSiteTermStoreGroupSetChildRelation', 
               'Get-MgSiteTermStoreGroupSetChildRelationCount', 
               'Get-MgSiteTermStoreGroupSetChildRelationFromTerm', 
               'Get-MgSiteTermStoreGroupSetChildRelationSet', 
               'Get-MgSiteTermStoreGroupSetChildRelationToTerm', 
               'Get-MgSiteTermStoreGroupSetChildSet', 
               'Get-MgSiteTermStoreGroupSetCount', 
               'Get-MgSiteTermStoreGroupSetParentGroup', 
               'Get-MgSiteTermStoreGroupSetRelation', 
               'Get-MgSiteTermStoreGroupSetRelationCount', 
               'Get-MgSiteTermStoreGroupSetRelationFromTerm', 
               'Get-MgSiteTermStoreGroupSetRelationSet', 
               'Get-MgSiteTermStoreGroupSetRelationToTerm', 
               'Get-MgSiteTermStoreGroupSetTerm', 
               'Get-MgSiteTermStoreGroupSetTermChild', 
               'Get-MgSiteTermStoreGroupSetTermChildCount', 
               'Get-MgSiteTermStoreGroupSetTermChildRelation', 
               'Get-MgSiteTermStoreGroupSetTermChildRelationCount', 
               'Get-MgSiteTermStoreGroupSetTermChildRelationFromTerm', 
               'Get-MgSiteTermStoreGroupSetTermChildRelationSet', 
               'Get-MgSiteTermStoreGroupSetTermChildRelationToTerm', 
               'Get-MgSiteTermStoreGroupSetTermChildSet', 
               'Get-MgSiteTermStoreGroupSetTermCount', 
               'Get-MgSiteTermStoreGroupSetTermRelation', 
               'Get-MgSiteTermStoreGroupSetTermRelationCount', 
               'Get-MgSiteTermStoreGroupSetTermRelationFromTerm', 
               'Get-MgSiteTermStoreGroupSetTermRelationSet', 
               'Get-MgSiteTermStoreGroupSetTermRelationToTerm', 
               'Get-MgSiteTermStoreGroupSetTermSet', 'Get-MgSiteTermStoreSet', 
               'Get-MgSiteTermStoreSetChild', 'Get-MgSiteTermStoreSetChildCount', 
               'Get-MgSiteTermStoreSetChildRelation', 
               'Get-MgSiteTermStoreSetChildRelationCount', 
               'Get-MgSiteTermStoreSetChildRelationFromTerm', 
               'Get-MgSiteTermStoreSetChildRelationSet', 
               'Get-MgSiteTermStoreSetChildRelationToTerm', 
               'Get-MgSiteTermStoreSetChildSet', 'Get-MgSiteTermStoreSetCount', 
               'Get-MgSiteTermStoreSetParentGroup', 
               'Get-MgSiteTermStoreSetParentGroupSet', 
               'Get-MgSiteTermStoreSetParentGroupSetChild', 
               'Get-MgSiteTermStoreSetParentGroupSetChildCount', 
               'Get-MgSiteTermStoreSetParentGroupSetChildRelation', 
               'Get-MgSiteTermStoreSetParentGroupSetChildRelationCount', 
               'Get-MgSiteTermStoreSetParentGroupSetChildRelationFromTerm', 
               'Get-MgSiteTermStoreSetParentGroupSetChildRelationSet', 
               'Get-MgSiteTermStoreSetParentGroupSetChildRelationToTerm', 
               'Get-MgSiteTermStoreSetParentGroupSetChildSet', 
               'Get-MgSiteTermStoreSetParentGroupSetCount', 
               'Get-MgSiteTermStoreSetParentGroupSetRelation', 
               'Get-MgSiteTermStoreSetParentGroupSetRelationCount', 
               'Get-MgSiteTermStoreSetParentGroupSetRelationFromTerm', 
               'Get-MgSiteTermStoreSetParentGroupSetRelationSet', 
               'Get-MgSiteTermStoreSetParentGroupSetRelationToTerm', 
               'Get-MgSiteTermStoreSetParentGroupSetTerm', 
               'Get-MgSiteTermStoreSetParentGroupSetTermChild', 
               'Get-MgSiteTermStoreSetParentGroupSetTermChildCount', 
               'Get-MgSiteTermStoreSetParentGroupSetTermChildRelation', 
               'Get-MgSiteTermStoreSetParentGroupSetTermChildRelationCount', 
               'Get-MgSiteTermStoreSetParentGroupSetTermChildRelationFromTerm', 
               'Get-MgSiteTermStoreSetParentGroupSetTermChildRelationSet', 
               'Get-MgSiteTermStoreSetParentGroupSetTermChildRelationToTerm', 
               'Get-MgSiteTermStoreSetParentGroupSetTermChildSet', 
               'Get-MgSiteTermStoreSetParentGroupSetTermCount', 
               'Get-MgSiteTermStoreSetParentGroupSetTermRelation', 
               'Get-MgSiteTermStoreSetParentGroupSetTermRelationCount', 
               'Get-MgSiteTermStoreSetParentGroupSetTermRelationFromTerm', 
               'Get-MgSiteTermStoreSetParentGroupSetTermRelationSet', 
               'Get-MgSiteTermStoreSetParentGroupSetTermRelationToTerm', 
               'Get-MgSiteTermStoreSetParentGroupSetTermSet', 
               'Get-MgSiteTermStoreSetRelation', 
               'Get-MgSiteTermStoreSetRelationCount', 
               'Get-MgSiteTermStoreSetRelationFromTerm', 
               'Get-MgSiteTermStoreSetRelationSet', 
               'Get-MgSiteTermStoreSetRelationToTerm', 
               'Get-MgSiteTermStoreSetTerm', 'Get-MgSiteTermStoreSetTermChild', 
               'Get-MgSiteTermStoreSetTermChildCount', 
               'Get-MgSiteTermStoreSetTermChildRelation', 
               'Get-MgSiteTermStoreSetTermChildRelationCount', 
               'Get-MgSiteTermStoreSetTermChildRelationFromTerm', 
               'Get-MgSiteTermStoreSetTermChildRelationSet', 
               'Get-MgSiteTermStoreSetTermChildRelationToTerm', 
               'Get-MgSiteTermStoreSetTermChildSet', 
               'Get-MgSiteTermStoreSetTermCount', 
               'Get-MgSiteTermStoreSetTermRelation', 
               'Get-MgSiteTermStoreSetTermRelationCount', 
               'Get-MgSiteTermStoreSetTermRelationFromTerm', 
               'Get-MgSiteTermStoreSetTermRelationSet', 
               'Get-MgSiteTermStoreSetTermRelationToTerm', 
               'Get-MgSiteTermStoreSetTermSet', 'Get-MgSubSite', 
               'Get-MgSubSiteCount', 'Get-MgUserFollowedSite', 
               'Get-MgUserFollowedSiteCount', 'Grant-MgSitePermission', 
               'Invoke-MgPreviewSiteOnenoteNotebookSectionGroupSectionPage', 
               'Invoke-MgPreviewSiteOnenoteNotebookSectionPage', 
               'Invoke-MgPreviewSiteOnenotePage', 
               'Invoke-MgPreviewSiteOnenoteSectionGroupSectionPage', 
               'Invoke-MgPreviewSiteOnenoteSectionPage', 
               'Invoke-MgReauthorizeSiteListSubscription', 
               'Join-MgSiteContentTypeWithHubSite', 
               'Join-MgSiteListContentTypeWithHubSite', 
               'New-MgGroupSiteAnalyticItemActivityStat', 
               'New-MgGroupSiteAnalyticItemActivityStatActivity', 
               'New-MgGroupSiteColumn', 'New-MgGroupSiteContentType', 
               'New-MgGroupSiteContentTypeColumn', 
               'New-MgGroupSiteContentTypeColumnLink', 
               'New-MgGroupSiteGetByPathColumn', 
               'New-MgGroupSiteGetByPathContentType', 
               'New-MgGroupSiteGetByPathList', 'New-MgGroupSiteGetByPathOperation', 
               'New-MgGroupSiteGetByPathPage', 
               'New-MgGroupSiteGetByPathPermission', 
               'New-MgGroupSiteGetByPathTermStore', 'New-MgGroupSiteList', 
               'New-MgGroupSiteListColumn', 'New-MgGroupSiteListContentType', 
               'New-MgGroupSiteListContentTypeColumn', 
               'New-MgGroupSiteListContentTypeColumnLink', 
               'New-MgGroupSiteListItem', 
               'New-MgGroupSiteListItemDocumentSetVersion', 
               'New-MgGroupSiteListItemVersion', 'New-MgGroupSiteListOperation', 
               'New-MgGroupSiteListSubscription', 'New-MgGroupSiteOnenoteNotebook', 
               'New-MgGroupSiteOnenoteNotebookSection', 
               'New-MgGroupSiteOnenoteNotebookSectionGroup', 
               'New-MgGroupSiteOnenoteNotebookSectionGroupSection', 
               'New-MgGroupSiteOnenoteNotebookSectionGroupSectionPage', 
               'New-MgGroupSiteOnenoteNotebookSectionPage', 
               'New-MgGroupSiteOnenoteOperation', 'New-MgGroupSiteOnenotePage', 
               'New-MgGroupSiteOnenoteResource', 'New-MgGroupSiteOnenoteSection', 
               'New-MgGroupSiteOnenoteSectionGroup', 
               'New-MgGroupSiteOnenoteSectionGroupSection', 
               'New-MgGroupSiteOnenoteSectionGroupSectionPage', 
               'New-MgGroupSiteOnenoteSectionPage', 'New-MgGroupSiteOperation', 
               'New-MgGroupSitePage', 
               'New-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSection', 
               'New-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSectionColumn', 
               'New-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSectionColumnWebpart', 
               'New-MgGroupSitePageAsSitePageCanvaLayoutVerticalSectionWebpart', 
               'New-MgGroupSitePageAsSitePageWebPart', 'New-MgGroupSitePermission', 
               'New-MgGroupSiteTermStore', 'New-MgGroupSiteTermStoreGroup', 
               'New-MgGroupSiteTermStoreGroupSet', 
               'New-MgGroupSiteTermStoreGroupSetChild', 
               'New-MgGroupSiteTermStoreGroupSetChildRelation', 
               'New-MgGroupSiteTermStoreGroupSetRelation', 
               'New-MgGroupSiteTermStoreGroupSetTerm', 
               'New-MgGroupSiteTermStoreGroupSetTermChild', 
               'New-MgGroupSiteTermStoreGroupSetTermChildRelation', 
               'New-MgGroupSiteTermStoreGroupSetTermRelation', 
               'New-MgGroupSiteTermStoreSet', 'New-MgGroupSiteTermStoreSetChild', 
               'New-MgGroupSiteTermStoreSetChildRelation', 
               'New-MgGroupSiteTermStoreSetParentGroupSet', 
               'New-MgGroupSiteTermStoreSetParentGroupSetChild', 
               'New-MgGroupSiteTermStoreSetParentGroupSetChildRelation', 
               'New-MgGroupSiteTermStoreSetParentGroupSetRelation', 
               'New-MgGroupSiteTermStoreSetParentGroupSetTerm', 
               'New-MgGroupSiteTermStoreSetParentGroupSetTermChild', 
               'New-MgGroupSiteTermStoreSetParentGroupSetTermChildRelation', 
               'New-MgGroupSiteTermStoreSetParentGroupSetTermRelation', 
               'New-MgGroupSiteTermStoreSetRelation', 
               'New-MgGroupSiteTermStoreSetTerm', 
               'New-MgGroupSiteTermStoreSetTermChild', 
               'New-MgGroupSiteTermStoreSetTermChildRelation', 
               'New-MgGroupSiteTermStoreSetTermRelation', 
               'New-MgSiteAnalyticItemActivityStat', 
               'New-MgSiteAnalyticItemActivityStatActivity', 'New-MgSiteColumn', 
               'New-MgSiteContentType', 'New-MgSiteContentTypeColumn', 
               'New-MgSiteContentTypeColumnLink', 'New-MgSiteGetByPathColumn', 
               'New-MgSiteGetByPathContentType', 'New-MgSiteGetByPathList', 
               'New-MgSiteGetByPathOperation', 'New-MgSiteGetByPathPage', 
               'New-MgSiteGetByPathPermission', 'New-MgSiteGetByPathTermStore', 
               'New-MgSiteList', 'New-MgSiteListColumn', 'New-MgSiteListContentType', 
               'New-MgSiteListContentTypeColumn', 
               'New-MgSiteListContentTypeColumnLink', 'New-MgSiteListItem', 
               'New-MgSiteListItemDocumentSetVersion', 'New-MgSiteListItemLink', 
               'New-MgSiteListItemVersion', 'New-MgSiteListOperation', 
               'New-MgSiteListSubscription', 'New-MgSiteOperation', 'New-MgSitePage', 
               'New-MgSitePageAsSitePageCanvaLayoutHorizontalSection', 
               'New-MgSitePageAsSitePageCanvaLayoutHorizontalSectionColumn', 
               'New-MgSitePageAsSitePageCanvaLayoutHorizontalSectionColumnWebpart', 
               'New-MgSitePageAsSitePageCanvaLayoutVerticalSectionWebpart', 
               'New-MgSitePageAsSitePageWebPart', 'New-MgSitePermission', 
               'New-MgSiteTermStore', 'New-MgSiteTermStoreGroup', 
               'New-MgSiteTermStoreGroupSet', 'New-MgSiteTermStoreGroupSetChild', 
               'New-MgSiteTermStoreGroupSetChildRelation', 
               'New-MgSiteTermStoreGroupSetRelation', 
               'New-MgSiteTermStoreGroupSetTerm', 
               'New-MgSiteTermStoreGroupSetTermChild', 
               'New-MgSiteTermStoreGroupSetTermChildRelation', 
               'New-MgSiteTermStoreGroupSetTermRelation', 'New-MgSiteTermStoreSet', 
               'New-MgSiteTermStoreSetChild', 
               'New-MgSiteTermStoreSetChildRelation', 
               'New-MgSiteTermStoreSetParentGroupSet', 
               'New-MgSiteTermStoreSetParentGroupSetChild', 
               'New-MgSiteTermStoreSetParentGroupSetChildRelation', 
               'New-MgSiteTermStoreSetParentGroupSetRelation', 
               'New-MgSiteTermStoreSetParentGroupSetTerm', 
               'New-MgSiteTermStoreSetParentGroupSetTermChild', 
               'New-MgSiteTermStoreSetParentGroupSetTermChildRelation', 
               'New-MgSiteTermStoreSetParentGroupSetTermRelation', 
               'New-MgSiteTermStoreSetRelation', 'New-MgSiteTermStoreSetTerm', 
               'New-MgSiteTermStoreSetTermChild', 
               'New-MgSiteTermStoreSetTermChildRelation', 
               'New-MgSiteTermStoreSetTermRelation', 'Publish-MgSiteContentType', 
               'Publish-MgSiteListContentType', 'Remove-MgAdminSharepoint', 
               'Remove-MgAdminSharepointSetting', 'Remove-MgGroupSiteAnalytic', 
               'Remove-MgGroupSiteAnalyticItemActivityStat', 
               'Remove-MgGroupSiteAnalyticItemActivityStatActivity', 
               'Remove-MgGroupSiteAnalyticItemActivityStatActivityDriveItemContent', 
               'Remove-MgGroupSiteColumn', 'Remove-MgGroupSiteContentType', 
               'Remove-MgGroupSiteContentTypeColumn', 
               'Remove-MgGroupSiteContentTypeColumnLink', 
               'Remove-MgGroupSiteGetByPathAnalytic', 
               'Remove-MgGroupSiteGetByPathOnenote', 
               'Remove-MgGroupSiteGetByPathTermStore', 'Remove-MgGroupSiteList', 
               'Remove-MgGroupSiteListColumn', 'Remove-MgGroupSiteListContentType', 
               'Remove-MgGroupSiteListContentTypeColumn', 
               'Remove-MgGroupSiteListContentTypeColumnLink', 
               'Remove-MgGroupSiteListItem', 
               'Remove-MgGroupSiteListItemDocumentSetVersion', 
               'Remove-MgGroupSiteListItemDocumentSetVersionField', 
               'Remove-MgGroupSiteListItemDriveItemContent', 
               'Remove-MgGroupSiteListItemField', 
               'Remove-MgGroupSiteListItemVersion', 
               'Remove-MgGroupSiteListItemVersionField', 
               'Remove-MgGroupSiteListOperation', 
               'Remove-MgGroupSiteListSubscription', 'Remove-MgGroupSiteOnenote', 
               'Remove-MgGroupSiteOnenoteNotebook', 
               'Remove-MgGroupSiteOnenoteNotebookSection', 
               'Remove-MgGroupSiteOnenoteNotebookSectionGroup', 
               'Remove-MgGroupSiteOnenoteNotebookSectionGroupSection', 
               'Remove-MgGroupSiteOnenoteNotebookSectionGroupSectionPage', 
               'Remove-MgGroupSiteOnenoteNotebookSectionGroupSectionPageContent', 
               'Remove-MgGroupSiteOnenoteNotebookSectionPage', 
               'Remove-MgGroupSiteOnenoteNotebookSectionPageContent', 
               'Remove-MgGroupSiteOnenoteOperation', 
               'Remove-MgGroupSiteOnenotePage', 
               'Remove-MgGroupSiteOnenotePageContent', 
               'Remove-MgGroupSiteOnenoteResource', 
               'Remove-MgGroupSiteOnenoteResourceContent', 
               'Remove-MgGroupSiteOnenoteSection', 
               'Remove-MgGroupSiteOnenoteSectionGroup', 
               'Remove-MgGroupSiteOnenoteSectionGroupSection', 
               'Remove-MgGroupSiteOnenoteSectionGroupSectionPage', 
               'Remove-MgGroupSiteOnenoteSectionGroupSectionPageContent', 
               'Remove-MgGroupSiteOnenoteSectionPage', 
               'Remove-MgGroupSiteOnenoteSectionPageContent', 
               'Remove-MgGroupSiteOperation', 'Remove-MgGroupSitePage', 
               'Remove-MgGroupSitePageAsSitePageCanvaLayout', 
               'Remove-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSection', 
               'Remove-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSectionColumn', 
               'Remove-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSectionColumnWebpart', 
               'Remove-MgGroupSitePageAsSitePageCanvaLayoutVerticalSection', 
               'Remove-MgGroupSitePageAsSitePageCanvaLayoutVerticalSectionWebpart', 
               'Remove-MgGroupSitePageAsSitePageWebPart', 
               'Remove-MgGroupSitePermission', 'Remove-MgGroupSiteTermStore', 
               'Remove-MgGroupSiteTermStoreGroup', 
               'Remove-MgGroupSiteTermStoreGroupSet', 
               'Remove-MgGroupSiteTermStoreGroupSetChild', 
               'Remove-MgGroupSiteTermStoreGroupSetChildRelation', 
               'Remove-MgGroupSiteTermStoreGroupSetParentGroup', 
               'Remove-MgGroupSiteTermStoreGroupSetRelation', 
               'Remove-MgGroupSiteTermStoreGroupSetTerm', 
               'Remove-MgGroupSiteTermStoreGroupSetTermChild', 
               'Remove-MgGroupSiteTermStoreGroupSetTermChildRelation', 
               'Remove-MgGroupSiteTermStoreGroupSetTermRelation', 
               'Remove-MgGroupSiteTermStoreSet', 
               'Remove-MgGroupSiteTermStoreSetChild', 
               'Remove-MgGroupSiteTermStoreSetChildRelation', 
               'Remove-MgGroupSiteTermStoreSetParentGroup', 
               'Remove-MgGroupSiteTermStoreSetParentGroupSet', 
               'Remove-MgGroupSiteTermStoreSetParentGroupSetChild', 
               'Remove-MgGroupSiteTermStoreSetParentGroupSetChildRelation', 
               'Remove-MgGroupSiteTermStoreSetParentGroupSetRelation', 
               'Remove-MgGroupSiteTermStoreSetParentGroupSetTerm', 
               'Remove-MgGroupSiteTermStoreSetParentGroupSetTermChild', 
               'Remove-MgGroupSiteTermStoreSetParentGroupSetTermChildRelation', 
               'Remove-MgGroupSiteTermStoreSetParentGroupSetTermRelation', 
               'Remove-MgGroupSiteTermStoreSetRelation', 
               'Remove-MgGroupSiteTermStoreSetTerm', 
               'Remove-MgGroupSiteTermStoreSetTermChild', 
               'Remove-MgGroupSiteTermStoreSetTermChildRelation', 
               'Remove-MgGroupSiteTermStoreSetTermRelation', 
               'Remove-MgSiteAnalytic', 'Remove-MgSiteAnalyticItemActivityStat', 
               'Remove-MgSiteAnalyticItemActivityStatActivity', 
               'Remove-MgSiteColumn', 'Remove-MgSiteContentType', 
               'Remove-MgSiteContentTypeColumn', 
               'Remove-MgSiteContentTypeColumnLink', 
               'Remove-MgSiteGetByPathAnalytic', 'Remove-MgSiteGetByPathTermStore', 
               'Remove-MgSiteList', 'Remove-MgSiteListColumn', 
               'Remove-MgSiteListContentType', 
               'Remove-MgSiteListContentTypeColumn', 
               'Remove-MgSiteListContentTypeColumnLink', 'Remove-MgSiteListItem', 
               'Remove-MgSiteListItemDocumentSetVersion', 
               'Remove-MgSiteListItemDocumentSetVersionField', 
               'Remove-MgSiteListItemField', 'Remove-MgSiteListItemVersion', 
               'Remove-MgSiteListItemVersionField', 'Remove-MgSiteListOperation', 
               'Remove-MgSiteListSubscription', 'Remove-MgSiteOperation', 
               'Remove-MgSitePage', 'Remove-MgSitePageAsSitePageCanvaLayout', 
               'Remove-MgSitePageAsSitePageCanvaLayoutHorizontalSection', 
               'Remove-MgSitePageAsSitePageCanvaLayoutHorizontalSectionColumn', 
               'Remove-MgSitePageAsSitePageCanvaLayoutHorizontalSectionColumnWebpart', 
               'Remove-MgSitePageAsSitePageCanvaLayoutVerticalSection', 
               'Remove-MgSitePageAsSitePageCanvaLayoutVerticalSectionWebpart', 
               'Remove-MgSitePageAsSitePageWebPart', 'Remove-MgSitePermission', 
               'Remove-MgSiteTermStore', 'Remove-MgSiteTermStoreGroup', 
               'Remove-MgSiteTermStoreGroupSet', 
               'Remove-MgSiteTermStoreGroupSetChild', 
               'Remove-MgSiteTermStoreGroupSetChildRelation', 
               'Remove-MgSiteTermStoreGroupSetParentGroup', 
               'Remove-MgSiteTermStoreGroupSetRelation', 
               'Remove-MgSiteTermStoreGroupSetTerm', 
               'Remove-MgSiteTermStoreGroupSetTermChild', 
               'Remove-MgSiteTermStoreGroupSetTermChildRelation', 
               'Remove-MgSiteTermStoreGroupSetTermRelation', 
               'Remove-MgSiteTermStoreSet', 'Remove-MgSiteTermStoreSetChild', 
               'Remove-MgSiteTermStoreSetChildRelation', 
               'Remove-MgSiteTermStoreSetParentGroup', 
               'Remove-MgSiteTermStoreSetParentGroupSet', 
               'Remove-MgSiteTermStoreSetParentGroupSetChild', 
               'Remove-MgSiteTermStoreSetParentGroupSetChildRelation', 
               'Remove-MgSiteTermStoreSetParentGroupSetRelation', 
               'Remove-MgSiteTermStoreSetParentGroupSetTerm', 
               'Remove-MgSiteTermStoreSetParentGroupSetTermChild', 
               'Remove-MgSiteTermStoreSetParentGroupSetTermChildRelation', 
               'Remove-MgSiteTermStoreSetParentGroupSetTermRelation', 
               'Remove-MgSiteTermStoreSetRelation', 
               'Remove-MgSiteTermStoreSetTerm', 
               'Remove-MgSiteTermStoreSetTermChild', 
               'Remove-MgSiteTermStoreSetTermChildRelation', 
               'Remove-MgSiteTermStoreSetTermRelation', 
               'Restore-MgSiteListItemDocumentSetVersion', 
               'Restore-MgSiteListItemVersion', 
               'Set-MgGroupSiteAnalyticItemActivityStatActivityDriveItemContent', 
               'Set-MgGroupSiteListItemDriveItemContent', 
               'Set-MgGroupSiteOnenoteNotebookSectionGroupSectionPageContent', 
               'Set-MgGroupSiteOnenoteNotebookSectionPageContent', 
               'Set-MgGroupSiteOnenotePageContent', 
               'Set-MgGroupSiteOnenoteResourceContent', 
               'Set-MgGroupSiteOnenoteSectionGroupSectionPageContent', 
               'Set-MgGroupSiteOnenoteSectionPageContent', 
               'Set-MgSiteAnalyticItemActivityStatActivityDriveItemContent', 
               'Set-MgSiteListItemDriveItemContent', 
               'Test-MgSiteContentTypePublished', 
               'Test-MgSiteListContentTypePublished', 
               'Unpublish-MgSiteContentType', 'Unpublish-MgSiteListContentType', 
               'Update-MgAdminSharepoint', 'Update-MgAdminSharepointSetting', 
               'Update-MgGroupSite', 'Update-MgGroupSiteAnalytic', 
               'Update-MgGroupSiteAnalyticItemActivityStat', 
               'Update-MgGroupSiteAnalyticItemActivityStatActivity', 
               'Update-MgGroupSiteColumn', 'Update-MgGroupSiteContentType', 
               'Update-MgGroupSiteContentTypeColumn', 
               'Update-MgGroupSiteContentTypeColumnLink', 
               'Update-MgGroupSiteCreatedByUserMailboxSetting', 
               'Update-MgGroupSiteGetByPathAnalytic', 
               'Update-MgGroupSiteGetByPathOnenote', 
               'Update-MgGroupSiteGetByPathTermStore', 
               'Update-MgGroupSiteLastModifiedByUserMailboxSetting', 
               'Update-MgGroupSiteList', 'Update-MgGroupSiteListColumn', 
               'Update-MgGroupSiteListContentType', 
               'Update-MgGroupSiteListContentTypeColumn', 
               'Update-MgGroupSiteListContentTypeColumnLink', 
               'Update-MgGroupSiteListCreatedByUserMailboxSetting', 
               'Update-MgGroupSiteListItem', 
               'Update-MgGroupSiteListItemCreatedByUserMailboxSetting', 
               'Update-MgGroupSiteListItemDocumentSetVersion', 
               'Update-MgGroupSiteListItemDocumentSetVersionField', 
               'Update-MgGroupSiteListItemField', 
               'Update-MgGroupSiteListItemLastModifiedByUserMailboxSetting', 
               'Update-MgGroupSiteListItemVersion', 
               'Update-MgGroupSiteListItemVersionField', 
               'Update-MgGroupSiteListLastModifiedByUserMailboxSetting', 
               'Update-MgGroupSiteListOperation', 
               'Update-MgGroupSiteListSubscription', 'Update-MgGroupSiteOnenote', 
               'Update-MgGroupSiteOnenoteNotebook', 
               'Update-MgGroupSiteOnenoteNotebookSection', 
               'Update-MgGroupSiteOnenoteNotebookSectionGroup', 
               'Update-MgGroupSiteOnenoteNotebookSectionGroupSection', 
               'Update-MgGroupSiteOnenoteNotebookSectionGroupSectionPage', 
               'Update-MgGroupSiteOnenoteNotebookSectionPage', 
               'Update-MgGroupSiteOnenoteOperation', 
               'Update-MgGroupSiteOnenotePage', 
               'Update-MgGroupSiteOnenoteResource', 
               'Update-MgGroupSiteOnenoteSection', 
               'Update-MgGroupSiteOnenoteSectionGroup', 
               'Update-MgGroupSiteOnenoteSectionGroupSection', 
               'Update-MgGroupSiteOnenoteSectionGroupSectionPage', 
               'Update-MgGroupSiteOnenoteSectionPage', 
               'Update-MgGroupSiteOperation', 'Update-MgGroupSitePage', 
               'Update-MgGroupSitePageAsSitePageCanvaLayout', 
               'Update-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSection', 
               'Update-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSectionColumn', 
               'Update-MgGroupSitePageAsSitePageCanvaLayoutHorizontalSectionColumnWebpart', 
               'Update-MgGroupSitePageAsSitePageCanvaLayoutVerticalSection', 
               'Update-MgGroupSitePageAsSitePageCanvaLayoutVerticalSectionWebpart', 
               'Update-MgGroupSitePageAsSitePageCreatedByUserMailboxSetting', 
               'Update-MgGroupSitePageAsSitePageLastModifiedByUserMailboxSetting', 
               'Update-MgGroupSitePageAsSitePageWebPart', 
               'Update-MgGroupSitePageCreatedByUserMailboxSetting', 
               'Update-MgGroupSitePageLastModifiedByUserMailboxSetting', 
               'Update-MgGroupSitePermission', 'Update-MgGroupSiteTermStore', 
               'Update-MgGroupSiteTermStoreGroup', 
               'Update-MgGroupSiteTermStoreGroupSet', 
               'Update-MgGroupSiteTermStoreGroupSetChild', 
               'Update-MgGroupSiteTermStoreGroupSetChildRelation', 
               'Update-MgGroupSiteTermStoreGroupSetParentGroup', 
               'Update-MgGroupSiteTermStoreGroupSetRelation', 
               'Update-MgGroupSiteTermStoreGroupSetTerm', 
               'Update-MgGroupSiteTermStoreGroupSetTermChild', 
               'Update-MgGroupSiteTermStoreGroupSetTermChildRelation', 
               'Update-MgGroupSiteTermStoreGroupSetTermRelation', 
               'Update-MgGroupSiteTermStoreSet', 
               'Update-MgGroupSiteTermStoreSetChild', 
               'Update-MgGroupSiteTermStoreSetChildRelation', 
               'Update-MgGroupSiteTermStoreSetParentGroup', 
               'Update-MgGroupSiteTermStoreSetParentGroupSet', 
               'Update-MgGroupSiteTermStoreSetParentGroupSetChild', 
               'Update-MgGroupSiteTermStoreSetParentGroupSetChildRelation', 
               'Update-MgGroupSiteTermStoreSetParentGroupSetRelation', 
               'Update-MgGroupSiteTermStoreSetParentGroupSetTerm', 
               'Update-MgGroupSiteTermStoreSetParentGroupSetTermChild', 
               'Update-MgGroupSiteTermStoreSetParentGroupSetTermChildRelation', 
               'Update-MgGroupSiteTermStoreSetParentGroupSetTermRelation', 
               'Update-MgGroupSiteTermStoreSetRelation', 
               'Update-MgGroupSiteTermStoreSetTerm', 
               'Update-MgGroupSiteTermStoreSetTermChild', 
               'Update-MgGroupSiteTermStoreSetTermChildRelation', 
               'Update-MgGroupSiteTermStoreSetTermRelation', 'Update-MgSite', 
               'Update-MgSiteAnalytic', 'Update-MgSiteAnalyticItemActivityStat', 
               'Update-MgSiteAnalyticItemActivityStatActivity', 
               'Update-MgSiteColumn', 'Update-MgSiteContentType', 
               'Update-MgSiteContentTypeColumn', 
               'Update-MgSiteContentTypeColumnLink', 
               'Update-MgSiteGetByPathAnalytic', 'Update-MgSiteGetByPathTermStore', 
               'Update-MgSiteList', 'Update-MgSiteListColumn', 
               'Update-MgSiteListContentType', 
               'Update-MgSiteListContentTypeColumn', 
               'Update-MgSiteListContentTypeColumnLink', 
               'Update-MgSiteListCreatedByUserMailboxSetting', 
               'Update-MgSiteListItem', 
               'Update-MgSiteListItemCreatedByUserMailboxSetting', 
               'Update-MgSiteListItemDocumentSetVersion', 
               'Update-MgSiteListItemDocumentSetVersionField', 
               'Update-MgSiteListItemField', 
               'Update-MgSiteListItemLastModifiedByUserMailboxSetting', 
               'Update-MgSiteListItemVersion', 'Update-MgSiteListItemVersionField', 
               'Update-MgSiteListLastModifiedByUserMailboxSetting', 
               'Update-MgSiteListOperation', 'Update-MgSiteListSubscription', 
               'Update-MgSiteOnenoteNotebookSectionGroupSectionPageContent', 
               'Update-MgSiteOnenoteNotebookSectionPageContent', 
               'Update-MgSiteOnenotePageContent', 
               'Update-MgSiteOnenoteSectionGroupSectionPageContent', 
               'Update-MgSiteOnenoteSectionPageContent', 'Update-MgSiteOperation', 
               'Update-MgSitePage', 'Update-MgSitePageAsSitePageCanvaLayout', 
               'Update-MgSitePageAsSitePageCanvaLayoutHorizontalSection', 
               'Update-MgSitePageAsSitePageCanvaLayoutHorizontalSectionColumn', 
               'Update-MgSitePageAsSitePageCanvaLayoutHorizontalSectionColumnWebpart', 
               'Update-MgSitePageAsSitePageCanvaLayoutVerticalSection', 
               'Update-MgSitePageAsSitePageCanvaLayoutVerticalSectionWebpart', 
               'Update-MgSitePageAsSitePageCreatedByUserMailboxSetting', 
               'Update-MgSitePageAsSitePageLastModifiedByUserMailboxSetting', 
               'Update-MgSitePageAsSitePageWebPart', 
               'Update-MgSitePageCreatedByUserMailboxSetting', 
               'Update-MgSitePageLastModifiedByUserMailboxSetting', 
               'Update-MgSitePermission', 'Update-MgSiteTermStore', 
               'Update-MgSiteTermStoreGroup', 'Update-MgSiteTermStoreGroupSet', 
               'Update-MgSiteTermStoreGroupSetChild', 
               'Update-MgSiteTermStoreGroupSetChildRelation', 
               'Update-MgSiteTermStoreGroupSetParentGroup', 
               'Update-MgSiteTermStoreGroupSetRelation', 
               'Update-MgSiteTermStoreGroupSetTerm', 
               'Update-MgSiteTermStoreGroupSetTermChild', 
               'Update-MgSiteTermStoreGroupSetTermChildRelation', 
               'Update-MgSiteTermStoreGroupSetTermRelation', 
               'Update-MgSiteTermStoreSet', 'Update-MgSiteTermStoreSetChild', 
               'Update-MgSiteTermStoreSetChildRelation', 
               'Update-MgSiteTermStoreSetParentGroup', 
               'Update-MgSiteTermStoreSetParentGroupSet', 
               'Update-MgSiteTermStoreSetParentGroupSetChild', 
               'Update-MgSiteTermStoreSetParentGroupSetChildRelation', 
               'Update-MgSiteTermStoreSetParentGroupSetRelation', 
               'Update-MgSiteTermStoreSetParentGroupSetTerm', 
               'Update-MgSiteTermStoreSetParentGroupSetTermChild', 
               'Update-MgSiteTermStoreSetParentGroupSetTermChildRelation', 
               'Update-MgSiteTermStoreSetParentGroupSetTermRelation', 
               'Update-MgSiteTermStoreSetRelation', 
               'Update-MgSiteTermStoreSetTerm', 
               'Update-MgSiteTermStoreSetTermChild', 
               'Update-MgSiteTermStoreSetTermChildRelation', 
               'Update-MgSiteTermStoreSetTermRelation'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoRgYJKoZIhvcNAQcCoIIoNzCCKDMCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAV0wcLO9LNT/8r
# 2ebJx1dAOEim1l5jk7X+XMF9HKOA/aCCDXYwggX0MIID3KADAgECAhMzAAAEBGx0
# Bv9XKydyAAAAAAQEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTE0WhcNMjUwOTExMjAxMTE0WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQC0KDfaY50MDqsEGdlIzDHBd6CqIMRQWW9Af1LHDDTuFjfDsvna0nEuDSYJmNyz
# NB10jpbg0lhvkT1AzfX2TLITSXwS8D+mBzGCWMM/wTpciWBV/pbjSazbzoKvRrNo
# DV/u9omOM2Eawyo5JJJdNkM2d8qzkQ0bRuRd4HarmGunSouyb9NY7egWN5E5lUc3
# a2AROzAdHdYpObpCOdeAY2P5XqtJkk79aROpzw16wCjdSn8qMzCBzR7rvH2WVkvF
# HLIxZQET1yhPb6lRmpgBQNnzidHV2Ocxjc8wNiIDzgbDkmlx54QPfw7RwQi8p1fy
# 4byhBrTjv568x8NGv3gwb0RbAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU8huhNbETDU+ZWllL4DNMPCijEU4w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMjkyMzAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAIjmD9IpQVvfB1QehvpC
# Ge7QeTQkKQ7j3bmDMjwSqFL4ri6ae9IFTdpywn5smmtSIyKYDn3/nHtaEn0X1NBj
# L5oP0BjAy1sqxD+uy35B+V8wv5GrxhMDJP8l2QjLtH/UglSTIhLqyt8bUAqVfyfp
# h4COMRvwwjTvChtCnUXXACuCXYHWalOoc0OU2oGN+mPJIJJxaNQc1sjBsMbGIWv3
# cmgSHkCEmrMv7yaidpePt6V+yPMik+eXw3IfZ5eNOiNgL1rZzgSJfTnvUqiaEQ0X
# dG1HbkDv9fv6CTq6m4Ty3IzLiwGSXYxRIXTxT4TYs5VxHy2uFjFXWVSL0J2ARTYL
# E4Oyl1wXDF1PX4bxg1yDMfKPHcE1Ijic5lx1KdK1SkaEJdto4hd++05J9Bf9TAmi
# u6EK6C9Oe5vRadroJCK26uCUI4zIjL/qG7mswW+qT0CW0gnR9JHkXCWNbo8ccMk1
# sJatmRoSAifbgzaYbUz8+lv+IXy5GFuAmLnNbGjacB3IMGpa+lbFgih57/fIhamq
# 5VhxgaEmn/UjWyr+cPiAFWuTVIpfsOjbEAww75wURNM1Imp9NJKye1O24EspEHmb
# DmqCUcq7NqkOKIG4PVm3hDDED/WQpzJDkvu4FrIbvyTGVU01vKsg4UfcdiZ0fQ+/
# V0hf8yrtq9CkB8iIuk5bBxuPMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGiYwghoiAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAQEbHQG/1crJ3IAAAAABAQwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIHFhgmMkJZj5C/oa6FRtX+0Y
# jLBS6hsd+2K1YjUEqUZ7MEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAssQYhWY2yid3cFcKPhHwxtzQPmEMvwdhymnGyALrs7CPbDj8Fwgk3pLR
# +IAkQSXGzE87rBPiRwJI8FDghJQPUh5sgpvlpVsBP5SlNRxZUZFUzy/rzBqI74Dc
# PeJr+S+8XiuYMvHQeYTCejvJf1o2Xe7+U8JIVCBLN//menIclumygNb11myYU58Z
# QIIs6oAJLAlKF6uzxRL3+GscFRgCAWycepkXgxoV18AGFFiAQV43V1MhwJWtfpe7
# r8L89Kt6tAJTCRDQLznqbsNHlbMCuJ/krkLdOttCsI4ZABqOIpC2wnVSoOgUbNCm
# 7OWMnSmVbIeRBn11wvdr95DwhYZExqGCF7AwghesBgorBgEEAYI3AwMBMYIXnDCC
# F5gGCSqGSIb3DQEHAqCCF4kwgheFAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFaBgsq
# hkiG9w0BCRABBKCCAUkEggFFMIIBQQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCBNWyg15Z8wtWbUnvZWHN8K44JBbTdd/ZaE6pY8iHiH4QIGZzvBpbw9
# GBMyMDI0MTEyMDE2NTg1Mi4wMDhaMASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# Tjo0MzFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaCCEf4wggcoMIIFEKADAgECAhMzAAAB+vs7RNN3M8bTAAEAAAH6MA0G
# CSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTI0
# MDcyNTE4MzExMVoXDTI1MTAyMjE4MzExMVowgdMxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9w
# ZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjQzMUEt
# MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyhZVBM3PZcBfEpAf7fII
# hygwYVVP64USeZbSlRR3pvJebva0LQCDW45yOrtpwIpGyDGX+EbCbHhS5Td4J0Yl
# c83ztLEbbQD7M6kqR0Xj+n82cGse/QnMH0WRZLnwggJdenpQ6UciM4nMYZvdQjyb
# A4qejOe9Y073JlXv3VIbdkQH2JGyT8oB/LsvPL/kAnJ45oQIp7Sx57RPQ/0O6qay
# J2SJrwcjA8auMdAnZKOixFlzoooh7SyycI7BENHTpkVKrRV5YelRvWNTg1pH4EC2
# KO2bxsBN23btMeTvZFieGIr+D8mf1lQQs0Ht/tMOVdah14t7Yk+xl5P4Tw3xfAGg
# Hsvsa6ugrxwmKTTX1kqXH5XCdw3TVeKCax6JV+ygM5i1NroJKwBCW11Pwi0z/ki9
# 0ZeO6XfEE9mCnJm76Qcxi3tnW/Y/3ZumKQ6X/iVIJo7Lk0Z/pATRwAINqwdvzpdt
# X2hOJib4GR8is2bpKks04GurfweWPn9z6jY7GBC+js8pSwGewrffwgAbNKm82ZDF
# vqBGQQVJwIHSXpjkS+G39eyYOG2rcILBIDlzUzMFFJbNh5tDv3GeJ3EKvC4vNSAx
# tGfaG/mQhK43YjevsB72LouU78rxtNhuMXSzaHq5fFiG3zcsYHaa4+w+YmMrhTEz
# D4SAish35BjoXP1P1Ct4Va0CAwEAAaOCAUkwggFFMB0GA1UdDgQWBBRjjHKbL5WV
# 6kd06KocQHphK9U/vzAfBgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
# BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmww
# bAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0El
# MjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUF
# BwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEAuFbCorFrvodG
# +ZNJH3Y+Nz5QpUytQVObOyYFrgcGrxq6MUa4yLmxN4xWdL1kygaW5BOZ3xBlPY7V
# puf5b5eaXP7qRq61xeOrX3f64kGiSWoRi9EJawJWCzJfUQRThDL4zxI2pYc1wnPp
# 7Q695bHqwZ02eaOBudh/IfEkGe0Ofj6IS3oyZsJP1yatcm4kBqIH6db1+weM4q46
# NhAfAf070zF6F+IpUHyhtMbQg5+QHfOuyBzrt67CiMJSKcJ3nMVyfNlnv6yvttYz
# LK3wS+0QwJUibLYJMI6FGcSuRxKlq6RjOhK9L3QOjh0VCM11rHM11ZmN0euJbbBC
# VfQEufOLNkG88MFCUNE10SSbM/Og/CbTko0M5wbVvQJ6CqLKjtHSoeoAGPeeX24f
# 5cPYyTcKlbM6LoUdO2P5JSdI5s1JF/On6LiUT50adpRstZajbYEeX/N7RvSbkn0d
# jD3BvT2Of3Wf9gIeaQIHbv1J2O/P5QOPQiVo8+0AKm6M0TKOduihhKxAt/6Yyk17
# Fv3RIdjT6wiL2qRIEsgOJp3fILw4mQRPu3spRfakSoQe5N0e4HWFf8WW2ZL0+c83
# Qzh3VtEPI6Y2e2BO/eWhTYbIbHpqYDfAtAYtaYIde87ZymXG3MO2wUjhL9HvSQzj
# oquq+OoUmvfBUcB2e5L6QCHO6qTO7WowggdxMIIFWaADAgECAhMzAAAAFcXna54C
# m0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UE
# CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZp
# Y2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAxODMy
# MjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0B
# AQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51
# yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY
# 6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9
# cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130/o5Tz9bshVZN
# 7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDua
# Rr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGpF1tnYN74
# kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2
# K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNOwTM5
# TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
# i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
# BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3Pmri
# Lq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUC
# BBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJl
# pxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIB
# FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9y
# eS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUA
# YgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
# 1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2Ny
# bC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0XzIw
# MTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
# Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/yp
# b+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulm
# ZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM
# 9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECW
# OKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2FzLixre24/LAl4
# FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3Uw
# xTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFXSVRk2XPX
# fx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVX
# VAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/AsGC
# onsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
# 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
# ahC0HVUzWLOhcGbyoYIDWTCCAkECAQEwggEBoYHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# Tjo0MzFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaIjCgEBMAcGBSsOAwIaAxUA94Z+bUJn+nKwBvII6sg0Ny7aPDaggYMw
# gYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsF
# AAIFAOroOkUwIhgPMjAyNDExMjAxMDM2NTNaGA8yMDI0MTEyMTEwMzY1M1owdzA9
# BgorBgEEAYRZCgQBMS8wLTAKAgUA6ug6RQIBADAKAgEAAgIXDgIB/zAHAgEAAgIT
# UjAKAgUA6umLxQIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAow
# CAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQC/V2sTtjnr
# Qfy5hsKPVYOYrMkNCGZokvWS1xHEkMKV6zPPmbVELPYKDypia09/T/LBJObRm0xb
# 71xOuxVj8sbTcgWIlaSIIsIc2j0zpnCPAnfI4IeN0B0eVkOeZWCZcKUh9f3ApONd
# EQKnTpxZD3Mi+Ex4lX9ZJ3TsF1N8V03SkhmXqc5lwIxrNNgj0ZSnQaBIp4aNULnU
# 5lqiWKFR6NmE5uWZkGS+UvG+wDNEpjF4KDXTunUP7URdWk7gpDfSHi1mYE2AumYm
# JpNDFchdiA9jja7u5GHsRDGwk7cCz/9J9WlcyCFSDk7z0wd6l7lKSnlZfWnVE05Z
# SzlDGsy3UfZEMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
# IDIwMTACEzMAAAH6+ztE03czxtMAAQAAAfowDQYJYIZIAWUDBAIBBQCgggFKMBoG
# CSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgo8akOXgf
# 2KSd5IWK+mMHDXcRMWPEm5LvvsB9IOm803EwgfoGCyqGSIb3DQEJEAIvMYHqMIHn
# MIHkMIG9BCB98n8tya8+B2jjU/dpJRIwHwHHpco5ogNStYocbkOeVjCBmDCBgKR+
# MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
# ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMT
# HU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB+vs7RNN3M8bTAAEA
# AAH6MCIEIAFMtmaYOXah+dOoV95q4FshBFjAPivjILwwAdbjqd/KMA0GCSqGSIb3
# DQEBCwUABIICAERnrSxYHoKvK/SfAZRFIKGRFgMXLNE+uort/ZMVSWL5XdDSnAMA
# YHrTPB5vD46VrTp6kyz578m2IOKytjS+zkbPE2S3tdzoT6jueRoAcnGH766G0WG/
# BnLBDrUfhJC+UkTg1TVfUFVxX9UT1Hz/ztAVNMV1tUAwNrwIRsOeSZR1H6u9gQXb
# Cb5rPs6YdQhipkkzsdNVOEmiQIJM6YwYa9XI91DGm+cXeyLhv7GUSWshOX0rmf7m
# n2Qzas6m68jY3KaG76pNUJe5sg6Vptq53OKqH3/BU+dV6oG82VCDFFvtE0syym+f
# Csb3QvveRJa+QVVc7h5fKJMWb5U3Y5OXGsRwvK/N0kouS8DUVe+Lky9FcOBzZ8r8
# ksuhpDS0Z42g2r+3DG54tNmCLyB+21k2crfzuDU8vVhat/cQT0qFaIOLgXp5mCjJ
# AZwsf3jgA9k2BMNusdNJefUDaOdYibUx7SiT1xDz3+fFzQOfvhxmwvdJnEEIk4VN
# wCj/nvQeaPvkXRV68pBhktWwjtkhtSMZIutvMfx7xfwoNjQdVhMeBTv12JGoPBzF
# hNz79C2zMSdbSTyLrMhNGuL4R2DZKCnbvY4WrEwzF1EJxAkG4upPHgIDO41vQjfh
# uCaSvkiDsefBMKKl17aQaOyU2LzbRAAMQ3ZVq72Cihm/7O2IN2f7gJfZ
# SIG # End signature block
