#
# Module manifest for module 'Microsoft.Graph.Teams'
#
# Generated by: Microsoft Corporation
#
# Generated on: 11/20/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Teams.psm1'

# Version number of this module.
ModuleVersion = '2.25.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'f8619bb2-8640-4d8d-baf5-0829db98fbe2'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.25.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Teams.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Teams.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgChatMember', 'Add-MgTeamChannelMember', 'Add-MgTeamMember', 
               'Add-MgTeamPrimaryChannelMember', 
               'Add-MgTeamworkDeletedTeamChannelMember', 
               'Clear-MgChatMessageReaction', 'Clear-MgChatMessageReplyReaction', 
               'Clear-MgTeamChannelMessageReaction', 
               'Clear-MgTeamChannelMessageReplyReaction', 
               'Clear-MgTeamPrimaryChannelMessageReaction', 
               'Clear-MgTeamPrimaryChannelMessageReplyReaction', 
               'Clear-MgTeamworkDeletedTeamChannelMessageReaction', 
               'Clear-MgTeamworkDeletedTeamChannelMessageReplyReaction', 
               'Complete-MgTeamChannelMigration', 'Complete-MgTeamMigration', 
               'Complete-MgTeamPrimaryChannelMigration', 
               'Complete-MgTeamworkDeletedTeamChannelMigration', 'Copy-MgTeam', 
               'Get-MgAllGroupTeamChannel', 'Get-MgAllGroupTeamChannelCount', 
               'Get-MgAllTeamChannel', 'Get-MgAllTeamChannelCount', 
               'Get-MgAllTeamMessage', 'Get-MgAllTeamworkDeletedTeamMessage', 
               'Get-MgAppCatalogTeamApp', 'Get-MgAppCatalogTeamAppCount', 
               'Get-MgAppCatalogTeamAppDefinition', 
               'Get-MgAppCatalogTeamAppDefinitionBot', 
               'Get-MgAppCatalogTeamAppDefinitionCount', 'Get-MgChat', 
               'Get-MgChatCount', 'Get-MgChatInstalledApp', 
               'Get-MgChatInstalledAppCount', 'Get-MgChatInstalledAppTeamApp', 
               'Get-MgChatInstalledAppTeamAppDefinition', 
               'Get-MgChatLastMessagePreview', 'Get-MgChatMember', 
               'Get-MgChatMemberCount', 'Get-MgChatMessage', 
               'Get-MgChatMessageCount', 'Get-MgChatMessageDelta', 
               'Get-MgChatMessageHostedContent', 
               'Get-MgChatMessageHostedContentCount', 'Get-MgChatMessageReply', 
               'Get-MgChatMessageReplyCount', 'Get-MgChatMessageReplyDelta', 
               'Get-MgChatMessageReplyHostedContent', 
               'Get-MgChatMessageReplyHostedContentCount', 
               'Get-MgChatPermissionGrant', 'Get-MgChatPermissionGrantCount', 
               'Get-MgChatPinnedMessage', 'Get-MgChatPinnedMessageCount', 
               'Get-MgChatRetainedMessage', 'Get-MgChatTab', 'Get-MgChatTabCount', 
               'Get-MgChatTabTeamApp', 'Get-MgGroupTeam', 'Get-MgGroupTeamChannel', 
               'Get-MgGroupTeamChannelCount', 'Get-MgGroupTeamChannelFileFolder', 
               'Get-MgGroupTeamChannelFileFolderContent', 
               'Get-MgGroupTeamChannelMember', 'Get-MgGroupTeamChannelMemberCount', 
               'Get-MgGroupTeamChannelMessage', 
               'Get-MgGroupTeamChannelMessageCount', 
               'Get-MgGroupTeamChannelMessageHostedContent', 
               'Get-MgGroupTeamChannelMessageHostedContentCount', 
               'Get-MgGroupTeamChannelMessageReply', 
               'Get-MgGroupTeamChannelMessageReplyCount', 
               'Get-MgGroupTeamChannelMessageReplyHostedContent', 
               'Get-MgGroupTeamChannelMessageReplyHostedContentCount', 
               'Get-MgGroupTeamChannelSharedWithTeam', 
               'Get-MgGroupTeamChannelSharedWithTeamAllowedMember', 
               'Get-MgGroupTeamChannelSharedWithTeamAllowedMemberCount', 
               'Get-MgGroupTeamChannelSharedWithTeamCount', 
               'Get-MgGroupTeamChannelTab', 'Get-MgGroupTeamChannelTabCount', 
               'Get-MgGroupTeamChannelTabTeamApp', 'Get-MgGroupTeamGroup', 
               'Get-MgGroupTeamGroupServiceProvisioningError', 
               'Get-MgGroupTeamGroupServiceProvisioningErrorCount', 
               'Get-MgGroupTeamIncomingChannel', 
               'Get-MgGroupTeamIncomingChannelCount', 
               'Get-MgGroupTeamInstalledApp', 'Get-MgGroupTeamInstalledAppCount', 
               'Get-MgGroupTeamInstalledAppTeamApp', 
               'Get-MgGroupTeamInstalledAppTeamAppDefinition', 
               'Get-MgGroupTeamMember', 'Get-MgGroupTeamMemberCount', 
               'Get-MgGroupTeamOperation', 'Get-MgGroupTeamOperationCount', 
               'Get-MgGroupTeamPermissionGrant', 
               'Get-MgGroupTeamPermissionGrantCount', 'Get-MgGroupTeamPhoto', 
               'Get-MgGroupTeamPhotoContent', 'Get-MgGroupTeamPrimaryChannel', 
               'Get-MgGroupTeamPrimaryChannelFileFolder', 
               'Get-MgGroupTeamPrimaryChannelFileFolderContent', 
               'Get-MgGroupTeamPrimaryChannelMember', 
               'Get-MgGroupTeamPrimaryChannelMemberCount', 
               'Get-MgGroupTeamPrimaryChannelMessage', 
               'Get-MgGroupTeamPrimaryChannelMessageCount', 
               'Get-MgGroupTeamPrimaryChannelMessageHostedContent', 
               'Get-MgGroupTeamPrimaryChannelMessageHostedContentCount', 
               'Get-MgGroupTeamPrimaryChannelMessageReply', 
               'Get-MgGroupTeamPrimaryChannelMessageReplyCount', 
               'Get-MgGroupTeamPrimaryChannelMessageReplyHostedContent', 
               'Get-MgGroupTeamPrimaryChannelMessageReplyHostedContentCount', 
               'Get-MgGroupTeamPrimaryChannelSharedWithTeam', 
               'Get-MgGroupTeamPrimaryChannelSharedWithTeamAllowedMember', 
               'Get-MgGroupTeamPrimaryChannelSharedWithTeamAllowedMemberCount', 
               'Get-MgGroupTeamPrimaryChannelSharedWithTeamCount', 
               'Get-MgGroupTeamPrimaryChannelTab', 
               'Get-MgGroupTeamPrimaryChannelTabCount', 
               'Get-MgGroupTeamPrimaryChannelTabTeamApp', 
               'Get-MgGroupTeamSchedule', 
               'Get-MgGroupTeamScheduleOfferShiftRequest', 
               'Get-MgGroupTeamScheduleOfferShiftRequestCount', 
               'Get-MgGroupTeamScheduleOpenShift', 
               'Get-MgGroupTeamScheduleOpenShiftChangeRequest', 
               'Get-MgGroupTeamScheduleOpenShiftChangeRequestCount', 
               'Get-MgGroupTeamScheduleOpenShiftCount', 
               'Get-MgGroupTeamScheduleSchedulingGroup', 
               'Get-MgGroupTeamScheduleSchedulingGroupCount', 
               'Get-MgGroupTeamScheduleShift', 'Get-MgGroupTeamScheduleShiftCount', 
               'Get-MgGroupTeamScheduleSwapShiftChangeRequest', 
               'Get-MgGroupTeamScheduleSwapShiftChangeRequestCount', 
               'Get-MgGroupTeamScheduleTimeOff', 
               'Get-MgGroupTeamScheduleTimeOffCount', 
               'Get-MgGroupTeamScheduleTimeOffReason', 
               'Get-MgGroupTeamScheduleTimeOffReasonCount', 
               'Get-MgGroupTeamScheduleTimeOffRequest', 
               'Get-MgGroupTeamScheduleTimeOffRequestCount', 'Get-MgGroupTeamTag', 
               'Get-MgGroupTeamTagCount', 'Get-MgGroupTeamTagMember', 
               'Get-MgGroupTeamTagMemberCount', 'Get-MgGroupTeamTemplate', 
               'Get-MgTeam', 'Get-MgTeamChannel', 'Get-MgTeamChannelCount', 
               'Get-MgTeamChannelFileFolder', 'Get-MgTeamChannelFileFolderContent', 
               'Get-MgTeamChannelMember', 'Get-MgTeamChannelMemberCount', 
               'Get-MgTeamChannelMessage', 'Get-MgTeamChannelMessageCount', 
               'Get-MgTeamChannelMessageDelta', 
               'Get-MgTeamChannelMessageHostedContent', 
               'Get-MgTeamChannelMessageHostedContentCount', 
               'Get-MgTeamChannelMessageReply', 
               'Get-MgTeamChannelMessageReplyCount', 
               'Get-MgTeamChannelMessageReplyDelta', 
               'Get-MgTeamChannelMessageReplyHostedContent', 
               'Get-MgTeamChannelMessageReplyHostedContentCount', 
               'Get-MgTeamChannelRetainedMessage', 
               'Get-MgTeamChannelSharedWithTeam', 
               'Get-MgTeamChannelSharedWithTeamAllowedMember', 
               'Get-MgTeamChannelSharedWithTeamAllowedMemberCount', 
               'Get-MgTeamChannelSharedWithTeamCount', 'Get-MgTeamChannelTab', 
               'Get-MgTeamChannelTabCount', 'Get-MgTeamChannelTabTeamApp', 
               'Get-MgTeamCount', 'Get-MgTeamGroupServiceProvisioningError', 
               'Get-MgTeamGroupServiceProvisioningErrorCount', 
               'Get-MgTeamIncomingChannel', 'Get-MgTeamIncomingChannelCount', 
               'Get-MgTeamInstalledApp', 'Get-MgTeamInstalledAppCount', 
               'Get-MgTeamInstalledAppTeamApp', 
               'Get-MgTeamInstalledAppTeamAppDefinition', 'Get-MgTeamMember', 
               'Get-MgTeamMemberCount', 'Get-MgTeamOperation', 
               'Get-MgTeamOperationCount', 'Get-MgTeamPermissionGrant', 
               'Get-MgTeamPermissionGrantCount', 'Get-MgTeamPhoto', 
               'Get-MgTeamPhotoContent', 'Get-MgTeamPrimaryChannel', 
               'Get-MgTeamPrimaryChannelFileFolder', 
               'Get-MgTeamPrimaryChannelFileFolderContent', 
               'Get-MgTeamPrimaryChannelMember', 
               'Get-MgTeamPrimaryChannelMemberCount', 
               'Get-MgTeamPrimaryChannelMessage', 
               'Get-MgTeamPrimaryChannelMessageCount', 
               'Get-MgTeamPrimaryChannelMessageDelta', 
               'Get-MgTeamPrimaryChannelMessageHostedContent', 
               'Get-MgTeamPrimaryChannelMessageHostedContentCount', 
               'Get-MgTeamPrimaryChannelMessageReply', 
               'Get-MgTeamPrimaryChannelMessageReplyCount', 
               'Get-MgTeamPrimaryChannelMessageReplyDelta', 
               'Get-MgTeamPrimaryChannelMessageReplyHostedContent', 
               'Get-MgTeamPrimaryChannelMessageReplyHostedContentCount', 
               'Get-MgTeamPrimaryChannelSharedWithTeam', 
               'Get-MgTeamPrimaryChannelSharedWithTeamAllowedMember', 
               'Get-MgTeamPrimaryChannelSharedWithTeamAllowedMemberCount', 
               'Get-MgTeamPrimaryChannelSharedWithTeamCount', 
               'Get-MgTeamPrimaryChannelTab', 'Get-MgTeamPrimaryChannelTabCount', 
               'Get-MgTeamPrimaryChannelTabTeamApp', 'Get-MgTeamSchedule', 
               'Get-MgTeamScheduleOfferShiftRequest', 
               'Get-MgTeamScheduleOfferShiftRequestCount', 
               'Get-MgTeamScheduleOpenShift', 
               'Get-MgTeamScheduleOpenShiftChangeRequest', 
               'Get-MgTeamScheduleOpenShiftChangeRequestCount', 
               'Get-MgTeamScheduleOpenShiftCount', 
               'Get-MgTeamScheduleSchedulingGroup', 
               'Get-MgTeamScheduleSchedulingGroupCount', 'Get-MgTeamScheduleShift', 
               'Get-MgTeamScheduleShiftCount', 
               'Get-MgTeamScheduleSwapShiftChangeRequest', 
               'Get-MgTeamScheduleSwapShiftChangeRequestCount', 
               'Get-MgTeamScheduleTimeOff', 'Get-MgTeamScheduleTimeOffCount', 
               'Get-MgTeamScheduleTimeOffReason', 
               'Get-MgTeamScheduleTimeOffReasonCount', 
               'Get-MgTeamScheduleTimeOffRequest', 
               'Get-MgTeamScheduleTimeOffRequestCount', 'Get-MgTeamTag', 
               'Get-MgTeamTagCount', 'Get-MgTeamTagMember', 
               'Get-MgTeamTagMemberCount', 'Get-MgTeamTemplate', 'Get-MgTeamwork', 
               'Get-MgTeamworkDeletedChat', 'Get-MgTeamworkDeletedChatCount', 
               'Get-MgTeamworkDeletedTeam', 'Get-MgTeamworkDeletedTeamChannel', 
               'Get-MgTeamworkDeletedTeamChannelCount', 
               'Get-MgTeamworkDeletedTeamChannelFileFolder', 
               'Get-MgTeamworkDeletedTeamChannelFileFolderContent', 
               'Get-MgTeamworkDeletedTeamChannelMember', 
               'Get-MgTeamworkDeletedTeamChannelMemberCount', 
               'Get-MgTeamworkDeletedTeamChannelMessage', 
               'Get-MgTeamworkDeletedTeamChannelMessageCount', 
               'Get-MgTeamworkDeletedTeamChannelMessageDelta', 
               'Get-MgTeamworkDeletedTeamChannelMessageHostedContent', 
               'Get-MgTeamworkDeletedTeamChannelMessageHostedContentCount', 
               'Get-MgTeamworkDeletedTeamChannelMessageReply', 
               'Get-MgTeamworkDeletedTeamChannelMessageReplyCount', 
               'Get-MgTeamworkDeletedTeamChannelMessageReplyDelta', 
               'Get-MgTeamworkDeletedTeamChannelMessageReplyHostedContent', 
               'Get-MgTeamworkDeletedTeamChannelMessageReplyHostedContentCount', 
               'Get-MgTeamworkDeletedTeamChannelRetainedMessage', 
               'Get-MgTeamworkDeletedTeamChannelSharedWithTeam', 
               'Get-MgTeamworkDeletedTeamChannelSharedWithTeamAllowedMember', 
               'Get-MgTeamworkDeletedTeamChannelSharedWithTeamAllowedMemberCount', 
               'Get-MgTeamworkDeletedTeamChannelSharedWithTeamCount', 
               'Get-MgTeamworkDeletedTeamChannelTab', 
               'Get-MgTeamworkDeletedTeamChannelTabCount', 
               'Get-MgTeamworkDeletedTeamChannelTabTeamApp', 
               'Get-MgTeamworkDeletedTeamCount', 'Get-MgTeamworkTeamAppSetting', 
               'Get-MgTeamworkWorkforceIntegration', 
               'Get-MgTeamworkWorkforceIntegrationCount', 'Get-MgUserChat', 
               'Get-MgUserChatCount', 'Get-MgUserChatInstalledApp', 
               'Get-MgUserChatInstalledAppCount', 
               'Get-MgUserChatInstalledAppTeamApp', 
               'Get-MgUserChatInstalledAppTeamAppDefinition', 
               'Get-MgUserChatLastMessagePreview', 'Get-MgUserChatMember', 
               'Get-MgUserChatMemberCount', 'Get-MgUserChatMessage', 
               'Get-MgUserChatMessageCount', 'Get-MgUserChatMessageHostedContent', 
               'Get-MgUserChatMessageHostedContentCount', 
               'Get-MgUserChatMessageReply', 'Get-MgUserChatMessageReplyCount', 
               'Get-MgUserChatMessageReplyHostedContent', 
               'Get-MgUserChatMessageReplyHostedContentCount', 
               'Get-MgUserChatPermissionGrant', 
               'Get-MgUserChatPermissionGrantCount', 'Get-MgUserChatPinnedMessage', 
               'Get-MgUserChatPinnedMessageCount', 'Get-MgUserChatTab', 
               'Get-MgUserChatTabCount', 'Get-MgUserChatTabTeamApp', 
               'Get-MgUserJoinedTeam', 'Get-MgUserTeamwork', 
               'Get-MgUserTeamworkAssociatedTeam', 
               'Get-MgUserTeamworkAssociatedTeamCount', 
               'Get-MgUserTeamworkInstalledApp', 
               'Get-MgUserTeamworkInstalledAppChat', 
               'Get-MgUserTeamworkInstalledAppCount', 
               'Get-MgUserTeamworkInstalledAppTeamApp', 
               'Get-MgUserTeamworkInstalledAppTeamAppDefinition', 
               'Hide-MgChatForUser', 'Invoke-MgArchiveTeam', 
               'Invoke-MgArchiveTeamChannel', 'Invoke-MgArchiveTeamPrimaryChannel', 
               'Invoke-MgArchiveTeamworkDeletedTeamChannel', 'Invoke-MgGraphChat', 
               'Invoke-MgHaveTeamChannel', 'Invoke-MgHaveTeamPrimaryChannel', 
               'Invoke-MgHaveTeamworkDeletedTeamChannel', 
               'Invoke-MgMarkChatReadForUser', 'Invoke-MgMarkChatUnreadForUser', 
               'Invoke-MgShareTeamSchedule', 'Invoke-MgSoftChatMessageDelete', 
               'Invoke-MgSoftChatMessageReplyDelete', 
               'Invoke-MgSoftTeamChannelMessageDelete', 
               'Invoke-MgSoftTeamChannelMessageReplyDelete', 
               'Invoke-MgSoftTeamPrimaryChannelMessageDelete', 
               'Invoke-MgSoftTeamPrimaryChannelMessageReplyDelete', 
               'Invoke-MgSoftTeamworkDeletedTeamChannelMessageDelete', 
               'Invoke-MgSoftTeamworkDeletedTeamChannelMessageReplyDelete', 
               'Invoke-MgUnarchiveTeam', 'Invoke-MgUnarchiveTeamChannel', 
               'Invoke-MgUnarchiveTeamPrimaryChannel', 
               'Invoke-MgUnarchiveTeamworkDeletedTeamChannel', 
               'New-MgAppCatalogTeamApp', 'New-MgAppCatalogTeamAppDefinition', 
               'New-MgChat', 'New-MgChatInstalledApp', 'New-MgChatMember', 
               'New-MgChatMessage', 'New-MgChatMessageHostedContent', 
               'New-MgChatMessageReply', 'New-MgChatMessageReplyHostedContent', 
               'New-MgChatPermissionGrant', 'New-MgChatPinnedMessage', 
               'New-MgChatTab', 'New-MgGroupTeamChannel', 
               'New-MgGroupTeamChannelMember', 'New-MgGroupTeamChannelMessage', 
               'New-MgGroupTeamChannelMessageHostedContent', 
               'New-MgGroupTeamChannelMessageReply', 
               'New-MgGroupTeamChannelMessageReplyHostedContent', 
               'New-MgGroupTeamChannelSharedWithTeam', 'New-MgGroupTeamChannelTab', 
               'New-MgGroupTeamInstalledApp', 'New-MgGroupTeamMember', 
               'New-MgGroupTeamOperation', 'New-MgGroupTeamPermissionGrant', 
               'New-MgGroupTeamPrimaryChannelMember', 
               'New-MgGroupTeamPrimaryChannelMessage', 
               'New-MgGroupTeamPrimaryChannelMessageHostedContent', 
               'New-MgGroupTeamPrimaryChannelMessageReply', 
               'New-MgGroupTeamPrimaryChannelMessageReplyHostedContent', 
               'New-MgGroupTeamPrimaryChannelSharedWithTeam', 
               'New-MgGroupTeamPrimaryChannelTab', 
               'New-MgGroupTeamScheduleOfferShiftRequest', 
               'New-MgGroupTeamScheduleOpenShift', 
               'New-MgGroupTeamScheduleOpenShiftChangeRequest', 
               'New-MgGroupTeamScheduleSchedulingGroup', 
               'New-MgGroupTeamScheduleShift', 
               'New-MgGroupTeamScheduleSwapShiftChangeRequest', 
               'New-MgGroupTeamScheduleTimeOff', 
               'New-MgGroupTeamScheduleTimeOffReason', 
               'New-MgGroupTeamScheduleTimeOffRequest', 'New-MgGroupTeamTag', 
               'New-MgGroupTeamTagMember', 'New-MgTeam', 'New-MgTeamChannel', 
               'New-MgTeamChannelEmail', 'New-MgTeamChannelMember', 
               'New-MgTeamChannelMessage', 'New-MgTeamChannelMessageHostedContent', 
               'New-MgTeamChannelMessageReply', 
               'New-MgTeamChannelMessageReplyHostedContent', 
               'New-MgTeamChannelSharedWithTeam', 'New-MgTeamChannelTab', 
               'New-MgTeamInstalledApp', 'New-MgTeamMember', 'New-MgTeamOperation', 
               'New-MgTeamPermissionGrant', 'New-MgTeamPrimaryChannelEmail', 
               'New-MgTeamPrimaryChannelMember', 'New-MgTeamPrimaryChannelMessage', 
               'New-MgTeamPrimaryChannelMessageHostedContent', 
               'New-MgTeamPrimaryChannelMessageReply', 
               'New-MgTeamPrimaryChannelMessageReplyHostedContent', 
               'New-MgTeamPrimaryChannelSharedWithTeam', 
               'New-MgTeamPrimaryChannelTab', 
               'New-MgTeamScheduleOfferShiftRequest', 
               'New-MgTeamScheduleOpenShift', 
               'New-MgTeamScheduleOpenShiftChangeRequest', 
               'New-MgTeamScheduleSchedulingGroup', 'New-MgTeamScheduleShift', 
               'New-MgTeamScheduleSwapShiftChangeRequest', 
               'New-MgTeamScheduleTimeOff', 'New-MgTeamScheduleTimeOffReason', 
               'New-MgTeamScheduleTimeOffRequest', 'New-MgTeamTag', 
               'New-MgTeamTagMember', 'New-MgTeamworkDeletedChat', 
               'New-MgTeamworkDeletedTeam', 'New-MgTeamworkDeletedTeamChannel', 
               'New-MgTeamworkDeletedTeamChannelEmail', 
               'New-MgTeamworkDeletedTeamChannelMember', 
               'New-MgTeamworkDeletedTeamChannelMessage', 
               'New-MgTeamworkDeletedTeamChannelMessageHostedContent', 
               'New-MgTeamworkDeletedTeamChannelMessageReply', 
               'New-MgTeamworkDeletedTeamChannelMessageReplyHostedContent', 
               'New-MgTeamworkDeletedTeamChannelSharedWithTeam', 
               'New-MgTeamworkDeletedTeamChannelTab', 
               'New-MgTeamworkWorkforceIntegration', 'New-MgUserChat', 
               'New-MgUserChatInstalledApp', 'New-MgUserChatMember', 
               'New-MgUserChatMessage', 'New-MgUserChatMessageHostedContent', 
               'New-MgUserChatMessageReply', 
               'New-MgUserChatMessageReplyHostedContent', 
               'New-MgUserChatPermissionGrant', 'New-MgUserChatPinnedMessage', 
               'New-MgUserChatTab', 'New-MgUserTeamworkAssociatedTeam', 
               'New-MgUserTeamworkInstalledApp', 'Remove-MgAppCatalogTeamApp', 
               'Remove-MgAppCatalogTeamAppDefinition', 
               'Remove-MgAppCatalogTeamAppDefinitionBot', 'Remove-MgChat', 
               'Remove-MgChatInstalledApp', 'Remove-MgChatLastMessagePreview', 
               'Remove-MgChatMember', 'Remove-MgChatMessageReplyHostedContent', 
               'Remove-MgChatPermissionGrant', 'Remove-MgChatPinnedMessage', 
               'Remove-MgChatTab', 'Remove-MgGroupTeam', 'Remove-MgGroupTeamChannel', 
               'Remove-MgGroupTeamChannelFileFolderContent', 
               'Remove-MgGroupTeamChannelMember', 
               'Remove-MgGroupTeamChannelMessage', 
               'Remove-MgGroupTeamChannelMessageHostedContent', 
               'Remove-MgGroupTeamChannelMessageReply', 
               'Remove-MgGroupTeamChannelMessageReplyHostedContent', 
               'Remove-MgGroupTeamChannelSharedWithTeam', 
               'Remove-MgGroupTeamChannelTab', 'Remove-MgGroupTeamInstalledApp', 
               'Remove-MgGroupTeamMember', 'Remove-MgGroupTeamOperation', 
               'Remove-MgGroupTeamPermissionGrant', 
               'Remove-MgGroupTeamPhotoContent', 
               'Remove-MgGroupTeamPrimaryChannel', 
               'Remove-MgGroupTeamPrimaryChannelFileFolderContent', 
               'Remove-MgGroupTeamPrimaryChannelMember', 
               'Remove-MgGroupTeamPrimaryChannelMessage', 
               'Remove-MgGroupTeamPrimaryChannelMessageHostedContent', 
               'Remove-MgGroupTeamPrimaryChannelMessageReply', 
               'Remove-MgGroupTeamPrimaryChannelMessageReplyHostedContent', 
               'Remove-MgGroupTeamPrimaryChannelSharedWithTeam', 
               'Remove-MgGroupTeamPrimaryChannelTab', 'Remove-MgGroupTeamSchedule', 
               'Remove-MgGroupTeamScheduleOfferShiftRequest', 
               'Remove-MgGroupTeamScheduleOpenShift', 
               'Remove-MgGroupTeamScheduleOpenShiftChangeRequest', 
               'Remove-MgGroupTeamScheduleSchedulingGroup', 
               'Remove-MgGroupTeamScheduleShift', 
               'Remove-MgGroupTeamScheduleSwapShiftChangeRequest', 
               'Remove-MgGroupTeamScheduleTimeOff', 
               'Remove-MgGroupTeamScheduleTimeOffReason', 
               'Remove-MgGroupTeamScheduleTimeOffRequest', 'Remove-MgGroupTeamTag', 
               'Remove-MgGroupTeamTagMember', 'Remove-MgTeam', 
               'Remove-MgTeamChannel', 'Remove-MgTeamChannelEmail', 
               'Remove-MgTeamChannelFileFolderContent', 
               'Remove-MgTeamChannelMember', 
               'Remove-MgTeamChannelMessageReplyHostedContent', 
               'Remove-MgTeamChannelSharedWithTeam', 'Remove-MgTeamChannelTab', 
               'Remove-MgTeamInstalledApp', 'Remove-MgTeamMember', 
               'Remove-MgTeamOperation', 'Remove-MgTeamPermissionGrant', 
               'Remove-MgTeamPhotoContent', 'Remove-MgTeamPrimaryChannel', 
               'Remove-MgTeamPrimaryChannelEmail', 
               'Remove-MgTeamPrimaryChannelFileFolderContent', 
               'Remove-MgTeamPrimaryChannelMember', 
               'Remove-MgTeamPrimaryChannelMessageReplyHostedContent', 
               'Remove-MgTeamPrimaryChannelSharedWithTeam', 
               'Remove-MgTeamPrimaryChannelTab', 'Remove-MgTeamSchedule', 
               'Remove-MgTeamScheduleOfferShiftRequest', 
               'Remove-MgTeamScheduleOpenShift', 
               'Remove-MgTeamScheduleOpenShiftChangeRequest', 
               'Remove-MgTeamScheduleSchedulingGroup', 
               'Remove-MgTeamScheduleShift', 
               'Remove-MgTeamScheduleSwapShiftChangeRequest', 
               'Remove-MgTeamScheduleTimeOff', 
               'Remove-MgTeamScheduleTimeOffReason', 
               'Remove-MgTeamScheduleTimeOffRequest', 'Remove-MgTeamTag', 
               'Remove-MgTeamTagMember', 'Remove-MgTeamworkDeletedChat', 
               'Remove-MgTeamworkDeletedTeam', 
               'Remove-MgTeamworkDeletedTeamChannel', 
               'Remove-MgTeamworkDeletedTeamChannelEmail', 
               'Remove-MgTeamworkDeletedTeamChannelFileFolderContent', 
               'Remove-MgTeamworkDeletedTeamChannelMember', 
               'Remove-MgTeamworkDeletedTeamChannelMessage', 
               'Remove-MgTeamworkDeletedTeamChannelMessageHostedContent', 
               'Remove-MgTeamworkDeletedTeamChannelMessageReply', 
               'Remove-MgTeamworkDeletedTeamChannelMessageReplyHostedContent', 
               'Remove-MgTeamworkDeletedTeamChannelSharedWithTeam', 
               'Remove-MgTeamworkDeletedTeamChannelTab', 
               'Remove-MgTeamworkTeamAppSetting', 
               'Remove-MgTeamworkWorkforceIntegration', 'Remove-MgUserChat', 
               'Remove-MgUserChatInstalledApp', 
               'Remove-MgUserChatLastMessagePreview', 'Remove-MgUserChatMember', 
               'Remove-MgUserChatMessage', 'Remove-MgUserChatMessageHostedContent', 
               'Remove-MgUserChatMessageReply', 
               'Remove-MgUserChatMessageReplyHostedContent', 
               'Remove-MgUserChatPermissionGrant', 
               'Remove-MgUserChatPinnedMessage', 'Remove-MgUserChatTab', 
               'Remove-MgUserTeamwork', 'Remove-MgUserTeamworkAssociatedTeam', 
               'Remove-MgUserTeamworkInstalledApp', 
               'Send-MgChatActivityNotification', 
               'Send-MgTeamActivityNotification', 
               'Send-MgTeamworkActivityNotificationToRecipient', 
               'Set-MgChatMessageHostedContent', 'Set-MgChatMessageReaction', 
               'Set-MgChatMessageReplyHostedContent', 
               'Set-MgChatMessageReplyReaction', 'Set-MgGroupTeam', 
               'Set-MgGroupTeamChannelFileFolderContent', 
               'Set-MgGroupTeamChannelMessageHostedContent', 
               'Set-MgGroupTeamChannelMessageReplyHostedContent', 
               'Set-MgGroupTeamPhotoContent', 
               'Set-MgGroupTeamPrimaryChannelFileFolderContent', 
               'Set-MgGroupTeamPrimaryChannelMessageHostedContent', 
               'Set-MgGroupTeamPrimaryChannelMessageReplyHostedContent', 
               'Set-MgGroupTeamSchedule', 'Set-MgTeamChannelFileFolderContent', 
               'Set-MgTeamChannelMessageHostedContent', 
               'Set-MgTeamChannelMessageReaction', 
               'Set-MgTeamChannelMessageReplyHostedContent', 
               'Set-MgTeamChannelMessageReplyReaction', 'Set-MgTeamPhotoContent', 
               'Set-MgTeamPrimaryChannelFileFolderContent', 
               'Set-MgTeamPrimaryChannelMessageHostedContent', 
               'Set-MgTeamPrimaryChannelMessageReaction', 
               'Set-MgTeamPrimaryChannelMessageReplyHostedContent', 
               'Set-MgTeamPrimaryChannelMessageReplyReaction', 
               'Set-MgTeamSchedule', 
               'Set-MgTeamworkDeletedTeamChannelFileFolderContent', 
               'Set-MgTeamworkDeletedTeamChannelMessageHostedContent', 
               'Set-MgTeamworkDeletedTeamChannelMessageReaction', 
               'Set-MgTeamworkDeletedTeamChannelMessageReplyHostedContent', 
               'Set-MgTeamworkDeletedTeamChannelMessageReplyReaction', 
               'Set-MgUserChatMessageHostedContent', 
               'Set-MgUserChatMessageReplyHostedContent', 
               'Undo-MgChatMessageReplySoftDelete', 'Undo-MgChatMessageSoftDelete', 
               'Undo-MgTeamChannelMessageReplySoftDelete', 
               'Undo-MgTeamChannelMessageSoftDelete', 
               'Undo-MgTeamPrimaryChannelMessageReplySoftDelete', 
               'Undo-MgTeamPrimaryChannelMessageSoftDelete', 
               'Undo-MgTeamworkDeletedChatDelete', 
               'Undo-MgTeamworkDeletedTeamChannelMessageReplySoftDelete', 
               'Undo-MgTeamworkDeletedTeamChannelMessageSoftDelete', 
               'Update-MgAppCatalogTeamApp', 
               'Update-MgAppCatalogTeamAppDefinition', 
               'Update-MgAppCatalogTeamAppDefinitionBot', 'Update-MgChat', 
               'Update-MgChatInstalledApp', 'Update-MgChatLastMessagePreview', 
               'Update-MgChatMember', 'Update-MgChatMessage', 
               'Update-MgChatMessageReply', 
               'Update-MgChatMessageReplyHostedContent', 
               'Update-MgChatPermissionGrant', 'Update-MgChatPinnedMessage', 
               'Update-MgChatTab', 'Update-MgGroupTeamChannel', 
               'Update-MgGroupTeamChannelMember', 
               'Update-MgGroupTeamChannelMessage', 
               'Update-MgGroupTeamChannelMessageHostedContent', 
               'Update-MgGroupTeamChannelMessageReply', 
               'Update-MgGroupTeamChannelMessageReplyHostedContent', 
               'Update-MgGroupTeamChannelSharedWithTeam', 
               'Update-MgGroupTeamChannelTab', 'Update-MgGroupTeamMember', 
               'Update-MgGroupTeamOperation', 'Update-MgGroupTeamPermissionGrant', 
               'Update-MgGroupTeamPhoto', 'Update-MgGroupTeamPrimaryChannel', 
               'Update-MgGroupTeamPrimaryChannelMember', 
               'Update-MgGroupTeamPrimaryChannelMessage', 
               'Update-MgGroupTeamPrimaryChannelMessageHostedContent', 
               'Update-MgGroupTeamPrimaryChannelMessageReply', 
               'Update-MgGroupTeamPrimaryChannelMessageReplyHostedContent', 
               'Update-MgGroupTeamPrimaryChannelSharedWithTeam', 
               'Update-MgGroupTeamPrimaryChannelTab', 
               'Update-MgGroupTeamScheduleOfferShiftRequest', 
               'Update-MgGroupTeamScheduleOpenShift', 
               'Update-MgGroupTeamScheduleOpenShiftChangeRequest', 
               'Update-MgGroupTeamScheduleSchedulingGroup', 
               'Update-MgGroupTeamScheduleShift', 
               'Update-MgGroupTeamScheduleSwapShiftChangeRequest', 
               'Update-MgGroupTeamScheduleTimeOff', 
               'Update-MgGroupTeamScheduleTimeOffReason', 
               'Update-MgGroupTeamScheduleTimeOffRequest', 'Update-MgGroupTeamTag', 
               'Update-MgGroupTeamTagMember', 'Update-MgTeam', 
               'Update-MgTeamChannel', 'Update-MgTeamChannelMember', 
               'Update-MgTeamChannelMessage', 'Update-MgTeamChannelMessageReply', 
               'Update-MgTeamChannelMessageReplyHostedContent', 
               'Update-MgTeamChannelSharedWithTeam', 'Update-MgTeamChannelTab', 
               'Update-MgTeamInstalledApp', 'Update-MgTeamMember', 
               'Update-MgTeamOperation', 'Update-MgTeamPermissionGrant', 
               'Update-MgTeamPhoto', 'Update-MgTeamPrimaryChannel', 
               'Update-MgTeamPrimaryChannelMember', 
               'Update-MgTeamPrimaryChannelMessage', 
               'Update-MgTeamPrimaryChannelMessageReply', 
               'Update-MgTeamPrimaryChannelMessageReplyHostedContent', 
               'Update-MgTeamPrimaryChannelSharedWithTeam', 
               'Update-MgTeamPrimaryChannelTab', 
               'Update-MgTeamScheduleOfferShiftRequest', 
               'Update-MgTeamScheduleOpenShift', 
               'Update-MgTeamScheduleOpenShiftChangeRequest', 
               'Update-MgTeamScheduleSchedulingGroup', 
               'Update-MgTeamScheduleShift', 
               'Update-MgTeamScheduleSwapShiftChangeRequest', 
               'Update-MgTeamScheduleTimeOff', 
               'Update-MgTeamScheduleTimeOffReason', 
               'Update-MgTeamScheduleTimeOffRequest', 'Update-MgTeamTag', 
               'Update-MgTeamTagMember', 'Update-MgTeamwork', 
               'Update-MgTeamworkDeletedChat', 'Update-MgTeamworkDeletedTeam', 
               'Update-MgTeamworkDeletedTeamChannel', 
               'Update-MgTeamworkDeletedTeamChannelMember', 
               'Update-MgTeamworkDeletedTeamChannelMessage', 
               'Update-MgTeamworkDeletedTeamChannelMessageHostedContent', 
               'Update-MgTeamworkDeletedTeamChannelMessageReply', 
               'Update-MgTeamworkDeletedTeamChannelMessageReplyHostedContent', 
               'Update-MgTeamworkDeletedTeamChannelSharedWithTeam', 
               'Update-MgTeamworkDeletedTeamChannelTab', 
               'Update-MgTeamworkTeamAppSetting', 
               'Update-MgTeamworkWorkforceIntegration', 'Update-MgUserChat', 
               'Update-MgUserChatLastMessagePreview', 'Update-MgUserChatMember', 
               'Update-MgUserChatMessage', 'Update-MgUserChatMessageHostedContent', 
               'Update-MgUserChatMessageReply', 
               'Update-MgUserChatMessageReplyHostedContent', 
               'Update-MgUserChatPermissionGrant', 
               'Update-MgUserChatPinnedMessage', 'Update-MgUserChatTab', 
               'Update-MgUserTeamwork', 'Update-MgUserTeamworkAssociatedTeam'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-MgGroupTeamAllChannelCount', 'Get-MgTeamAllChannelCount', 
               'Get-MgTeamMessage', 'Get-MgTeamworkDeletedTeamMessage'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoKgYJKoZIhvcNAQcCoIIoGzCCKBcCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDnP5LOjU34lNQv
# i7ZdQXA2om0l97N6gr37sw3pUdYBeqCCDXYwggX0MIID3KADAgECAhMzAAAEBGx0
# Bv9XKydyAAAAAAQEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTE0WhcNMjUwOTExMjAxMTE0WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQC0KDfaY50MDqsEGdlIzDHBd6CqIMRQWW9Af1LHDDTuFjfDsvna0nEuDSYJmNyz
# NB10jpbg0lhvkT1AzfX2TLITSXwS8D+mBzGCWMM/wTpciWBV/pbjSazbzoKvRrNo
# DV/u9omOM2Eawyo5JJJdNkM2d8qzkQ0bRuRd4HarmGunSouyb9NY7egWN5E5lUc3
# a2AROzAdHdYpObpCOdeAY2P5XqtJkk79aROpzw16wCjdSn8qMzCBzR7rvH2WVkvF
# HLIxZQET1yhPb6lRmpgBQNnzidHV2Ocxjc8wNiIDzgbDkmlx54QPfw7RwQi8p1fy
# 4byhBrTjv568x8NGv3gwb0RbAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU8huhNbETDU+ZWllL4DNMPCijEU4w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMjkyMzAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAIjmD9IpQVvfB1QehvpC
# Ge7QeTQkKQ7j3bmDMjwSqFL4ri6ae9IFTdpywn5smmtSIyKYDn3/nHtaEn0X1NBj
# L5oP0BjAy1sqxD+uy35B+V8wv5GrxhMDJP8l2QjLtH/UglSTIhLqyt8bUAqVfyfp
# h4COMRvwwjTvChtCnUXXACuCXYHWalOoc0OU2oGN+mPJIJJxaNQc1sjBsMbGIWv3
# cmgSHkCEmrMv7yaidpePt6V+yPMik+eXw3IfZ5eNOiNgL1rZzgSJfTnvUqiaEQ0X
# dG1HbkDv9fv6CTq6m4Ty3IzLiwGSXYxRIXTxT4TYs5VxHy2uFjFXWVSL0J2ARTYL
# E4Oyl1wXDF1PX4bxg1yDMfKPHcE1Ijic5lx1KdK1SkaEJdto4hd++05J9Bf9TAmi
# u6EK6C9Oe5vRadroJCK26uCUI4zIjL/qG7mswW+qT0CW0gnR9JHkXCWNbo8ccMk1
# sJatmRoSAifbgzaYbUz8+lv+IXy5GFuAmLnNbGjacB3IMGpa+lbFgih57/fIhamq
# 5VhxgaEmn/UjWyr+cPiAFWuTVIpfsOjbEAww75wURNM1Imp9NJKye1O24EspEHmb
# DmqCUcq7NqkOKIG4PVm3hDDED/WQpzJDkvu4FrIbvyTGVU01vKsg4UfcdiZ0fQ+/
# V0hf8yrtq9CkB8iIuk5bBxuPMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGgowghoGAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAQEbHQG/1crJ3IAAAAABAQwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIPmEPtmTqA1JEwla+wkMXH6H
# tKh27d8G+5BPQtw28zAeMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAOe/LoW1QCOYabZ8RlAgCub47r9oyhb7eRVD/qkPbgXAIyejDNPDzAaNS
# KfhoHK9G9F1PGQbdDR9nYyKCUjga0s/ddJ2vwjF4NPyCW80W0jPaB7S/7c/HDVQQ
# 7zfo0H38WXuRCob9gruGK6pEs7ty7qSi3JlrVo9FOUFEFkFLekTEudeaNPRk0zZ1
# nSRqRckuxQg9fh9E0mILgoW7L4lMThd9VlfZxOD6m1vOvTb46qk2agy/hvrRAb07
# nHEAr5SXt/x2MyI/H/n5zBslITYr2TFlk+WYgEeb53wWzD1SJZFA8fGsGRbyJfRf
# 8JMX0S29FqKHTM62fycsWpHKEyv7OqGCF5QwgheQBgorBgEEAYI3AwMBMYIXgDCC
# F3wGCSqGSIb3DQEHAqCCF20wghdpAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFSBgsq
# hkiG9w0BCRABBKCCAUEEggE9MIIBOQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCBYbbtbKytMEn9mfANSKm+zqTuXAYrkgD/7Mu3jIcPiNQIGZzuxov4w
# GBMyMDI0MTEyMDE2NTg1My4wOTJaMASAAgH0oIHRpIHOMIHLMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1l
# cmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046ODYwMy0w
# NUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wg
# ghHqMIIHIDCCBQigAwIBAgITMwAAAfGzRfUn6MAW1gABAAAB8TANBgkqhkiG9w0B
# AQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yMzEyMDYxODQ1
# NTVaFw0yNTAzMDUxODQ1NTVaMIHLMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25z
# MScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046ODYwMy0wNUUwLUQ5NDcxJTAjBgNV
# BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggIiMA0GCSqGSIb3DQEB
# AQUAA4ICDwAwggIKAoICAQCxulCZttIf8X97rW9/J+Q4Vg9PiugB1ya1/DRxxLW2
# hwy4QgtU3j5fV75ZKa6XTTQhW5ClkGl6gp1nd5VBsx4Jb+oU4PsMA2foe8gP9bQN
# PVxIHMJu6TYcrrn39Hddet2xkdqUhzzySXaPFqFMk2VifEfj+HR6JheNs2LLzm8F
# DJm+pBddPDLag/R+APIWHyftq9itwM0WP5Z0dfQyI4WlVeUS+votsPbWm+RKsH4F
# QNhzb0t/D4iutcfCK3/LK+xLmS6dmAh7AMKuEUl8i2kdWBDRcc+JWa21SCefx5SP
# hJEFgYhdGPAop3G1l8T33cqrbLtcFJqww4TQiYiCkdysCcnIF0ZqSNAHcfI9SAv3
# gfkyxqQNJJ3sTsg5GPRF95mqgbfQbkFnU17iYbRIPJqwgSLhyB833ZDgmzxbKmJm
# dDabbzS0yGhngHa6+gwVaOUqcHf9w6kwxMo+OqG3QZIcwd5wHECs5rAJZ6PIyFM7
# Ad2hRUFHRTi353I7V4xEgYGuZb6qFx6Pf44i7AjXbptUolDcVzYEdgLQSWiuFajS
# 6Xg3k7Cy8TiM5HPUK9LZInloTxuULSxJmJ7nTjUjOj5xwRmC7x2S/mxql8nvHSCN
# 1OED2/wECOot6MEe9bL3nzoKwO8TNlEStq5scd25GA0gMQO+qNXV/xTDOBTJ8zBc
# GQIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFLy2xe59sCE0SjycqE5Erb4YrS1gMB8G
# A1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1UdHwRYMFYwVKBSoFCG
# Tmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29mdCUy
# MFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggrBgEFBQcBAQRgMF4w
# XAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2Vy
# dHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3J0MAwG
# A1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwDgYDVR0PAQH/BAQD
# AgeAMA0GCSqGSIb3DQEBCwUAA4ICAQDhSEjSBFSCbJyl3U/QmFMW2eLPBknnlsfI
# D/7gTMvANEnhq08I9HHbbqiwqDEHSvARvKtL7j0znICYBbMrVSmvgDxU8jAGqMyi
# LoM80788So3+T6IZV//UZRJqBl4oM3bCIQgFGo0VTeQ6RzYL+t1zCUXmmpPmM4xc
# ScVFATXj5Tx7By4ShWUC7Vhm7picDiU5igGjuivRhxPvbpflbh/bsiE5tx5cuOJE
# JSG+uWcqByR7TC4cGvuavHSjk1iRXT/QjaOEeJoOnfesbOdvJrJdbm+leYLRI67N
# 3cd8B/suU21tRdgwOnTk2hOuZKs/kLwaX6NsAbUy9pKsDmTyoWnGmyTWBPiTb2rp
# 5ogo8Y8hMU1YQs7rHR5hqilEq88jF+9H8Kccb/1ismJTGnBnRMv68Ud2l5LFhOZ4
# nRtl4lHri+N1L8EBg7aE8EvPe8Ca9gz8sh2F4COTYd1PHce1ugLvvWW1+aOSpd8N
# nwEid4zgD79ZQxisJqyO4lMWMzAgEeFhUm40FshtzXudAsX5LoCil4rLbHfwYtGO
# pw9DVX3jXAV90tG9iRbcqjtt3vhW9T+L3fAZlMeraWfh7eUmPltMU8lEQOMelo/1
# ehkIGO7YZOHxUqeKpmF9QaW8LXTT090AHZ4k6g+tdpZFfCMotyG+E4XqN6ZWtKEB
# QiE3xL27BDCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZI
# hvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# MjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAy
# MDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
# bWUtU3RhbXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
# AQDk4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX9gF/bErg4r25Phdg
# M/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPF
# dvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6
# GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBp
# Dco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL64NF50Zu
# yjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3E
# XzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0
# lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1q
# GFphAXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ
# +QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PA
# PBXbGjfHCBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkw
# EgYJKwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxG
# NSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARV
# MFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWlj
# cm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAK
# BggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMC
# AYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvX
# zpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20v
# cGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYI
# KwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG
# 9w0BAQsFAAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0x
# M7U518JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmC
# VgADsAW+iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449
# xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wM
# nosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDS
# PeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2d
# Y3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxn
# GSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+Crvs
# QWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokL
# jzbaukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL
# 6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggNN
# MIICNQIBATCB+aGB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
# bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
# b3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEn
# MCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjg2MDMtMDVFMC1EOTQ3MSUwIwYDVQQD
# ExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQD7
# n7Bk4gsM2tbU/i+M3BtRnLj096CBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA6ugqOTAiGA8yMDI0MTEyMDA5Mjgy
# NVoYDzIwMjQxMTIxMDkyODI1WjB0MDoGCisGAQQBhFkKBAExLDAqMAoCBQDq6Co5
# AgEAMAcCAQACAh8JMAcCAQACAhPWMAoCBQDq6Xu5AgEAMDYGCisGAQQBhFkKBAIx
# KDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZI
# hvcNAQELBQADggEBACeBKquXt+g45CnC5eVPKg9mTj2HueeDIZfx9/3mqK3pSes7
# 49EBdR73l9UEA6DnEXsPhBiXqMk1vRxG+qJYsxRGzP/JWJPj9p0jA2xt+N06VUU8
# iXbwbWAUY/gBsnQRTXXGkpzLR5gN4edHefuk5NmiIFicqXpaMOSDbqPAURsPrRMW
# m5WCymH+dH4H298RPpJBvVSN7lZDY0HqyYmOxODT3NM87Ypm3wZqq53R91wUqgQP
# XFU5qOfRVhxXfcwxrjcA8ow0jBZ5X2yvScg/QpXTKj5KcXRaUU1sHhRVL0x84AU8
# 0f4pCr99ss83n6vNUbKyNociwafRWGH59NreWJsxggQNMIIECQIBATCBkzB8MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNy
# b3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAfGzRfUn6MAW1gABAAAB8TAN
# BglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMC8G
# CSqGSIb3DQEJBDEiBCDXpvDv80uGuFpE9gt6AInLTA7hEPnC6KEjSvzR4KMDSjCB
# +gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EINV3/T5hS7ijwao466RosB7wwEib
# t0a1P5EqIwEj9hF4MIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTACEzMAAAHxs0X1J+jAFtYAAQAAAfEwIgQgNng8MSnmWbcUcjtOdRWpF5O7VBGM
# dnU/BofWsOkr6FkwDQYJKoZIhvcNAQELBQAEggIAVGN5dhL+bhvNJDpP4+D4K2It
# mSqhrr8/Ol3dhQArEu6djBft/i8Znlc4UW1skzGD+uMXjRyZt1asM6zWHiy8ukjx
# T8NI1t52rS9HrcjIiRukHA6/8Hsa1PEylrXPc/akR8ZGNxqAc1Ialz3yF1gmQtC0
# z/k2LQZ7MMEO/tf0osRoX4PYu+GULs9DvDtR2HkPZr7Bxq8CYS0kdKAQlchDkQ9f
# DxhswxCUsSmGoI590lS2KVMWKyPhEBSEBcl0D2fi3OValsu0iy6mpnXTXcvYe9db
# jCaHx9vMcE4rvatnuN4Cfk8ptB7pnwMd2jTelNutyZiTa6L3j1UIJXOS1etcMPeM
# 9i4uhBDVDiU3y1eOgmL80PYp18ZAWV5zEzysnaEcgVVKAfqrxyxfVcpV5PNGOpBH
# 4QpDXpPl1G7ucQkW74pgCGhkWqgxuXHqU3Lb8CcidCtzLfx7Q/FoePLUSS8aiU26
# 5ZWvXZRhjz1u+Ycwk8rqZfLoCCq9AbDyTWdJ2H07QTU8r81xsK9m6k3+mfw+Az10
# e+Z+0s9wUPR7FHblEklolIvmbk76PIw8lau4h0PanaE2PjtThww4jcDs7K1A4oGC
# cKPQtlwj6hx1dr5qSdj7abrUaoVkAXPcYgwejZZig/efqPQSNy7mGkGEfXKxBQUA
# WPPyq3cm9K9FaDnpxYw=
# SIG # End signature block
