#
# Module manifest for module 'Microsoft.Graph.Security'
#
# Generated by: Microsoft Corporation
#
# Generated on: 11/20/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Security.psm1'

# Version number of this module.
ModuleVersion = '2.25.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '06b0769e-2c63-4d60-9fb4-9ca0ec87e0d7'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.25.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Security.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Security.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgSecurityCaseEdiscoveryCaseCustodianHold', 
               'Add-MgSecurityCaseEdiscoveryCaseNoncustodialDataSourceHold', 
               'Add-MgSecurityCaseEdiscoveryCaseReviewSetQueryTag', 
               'Add-MgSecurityCaseEdiscoveryCaseReviewSetToReviewSet', 
               'Clear-MgSecurityCaseEdiscoveryCaseSearchData', 
               'Close-MgSecurityCaseEdiscoveryCase', 
               'Export-MgSecurityCaseEdiscoveryCaseReviewSet', 
               'Export-MgSecurityCaseEdiscoveryCaseReviewSetQuery', 
               'Get-MgSecurityAlert', 'Get-MgSecurityAlertCount', 
               'Get-MgSecurityAlertV2', 'Get-MgSecurityAlertV2Count', 
               'Get-MgSecurityAttackSimulation', 
               'Get-MgSecurityAttackSimulationAutomation', 
               'Get-MgSecurityAttackSimulationAutomationCount', 
               'Get-MgSecurityAttackSimulationAutomationRun', 
               'Get-MgSecurityAttackSimulationAutomationRunCount', 
               'Get-MgSecurityAttackSimulationCount', 
               'Get-MgSecurityAttackSimulationEndUserNotification', 
               'Get-MgSecurityAttackSimulationEndUserNotificationCount', 
               'Get-MgSecurityAttackSimulationEndUserNotificationDetail', 
               'Get-MgSecurityAttackSimulationEndUserNotificationDetailCount', 
               'Get-MgSecurityAttackSimulationLandingPage', 
               'Get-MgSecurityAttackSimulationLandingPageCount', 
               'Get-MgSecurityAttackSimulationLandingPageDetail', 
               'Get-MgSecurityAttackSimulationLandingPageDetailCount', 
               'Get-MgSecurityAttackSimulationLoginPage', 
               'Get-MgSecurityAttackSimulationLoginPageCount', 
               'Get-MgSecurityAttackSimulationOperation', 
               'Get-MgSecurityAttackSimulationOperationCount', 
               'Get-MgSecurityAttackSimulationPayload', 
               'Get-MgSecurityAttackSimulationPayloadCount', 
               'Get-MgSecurityAttackSimulationTraining', 
               'Get-MgSecurityAttackSimulationTrainingCount', 
               'Get-MgSecurityAttackSimulationTrainingLanguageDetail', 
               'Get-MgSecurityAttackSimulationTrainingLanguageDetailCount', 
               'Get-MgSecurityCase', 'Get-MgSecurityCaseEdiscoveryCase', 
               'Get-MgSecurityCaseEdiscoveryCaseCount', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodian', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodianCount', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodianLastIndexOperation', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodianSiteSource', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodianSiteSourceCount', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodianSiteSourceSite', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSource', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSourceCount', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSourceGroup', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSourceGroupServiceProvisioningError', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSourceGroupServiceProvisioningErrorCount', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodianUserSource', 
               'Get-MgSecurityCaseEdiscoveryCaseCustodianUserSourceCount', 
               'Get-MgSecurityCaseEdiscoveryCaseNoncustodialDataSource', 
               'Get-MgSecurityCaseEdiscoveryCaseNoncustodialDataSourceCount', 
               'Get-MgSecurityCaseEdiscoveryCaseNoncustodialDataSourceLastIndexOperation', 
               'Get-MgSecurityCaseEdiscoveryCaseOperation', 
               'Get-MgSecurityCaseEdiscoveryCaseOperationCount', 
               'Get-MgSecurityCaseEdiscoveryCaseReviewSet', 
               'Get-MgSecurityCaseEdiscoveryCaseReviewSetCount', 
               'Get-MgSecurityCaseEdiscoveryCaseReviewSetQuery', 
               'Get-MgSecurityCaseEdiscoveryCaseReviewSetQueryCount', 
               'Get-MgSecurityCaseEdiscoveryCaseSearch', 
               'Get-MgSecurityCaseEdiscoveryCaseSearchAdditionalSource', 
               'Get-MgSecurityCaseEdiscoveryCaseSearchAdditionalSourceCount', 
               'Get-MgSecurityCaseEdiscoveryCaseSearchAddToReviewSetOperation', 
               'Get-MgSecurityCaseEdiscoveryCaseSearchCount', 
               'Get-MgSecurityCaseEdiscoveryCaseSearchCustodianSource', 
               'Get-MgSecurityCaseEdiscoveryCaseSearchCustodianSourceCount', 
               'Get-MgSecurityCaseEdiscoveryCaseSearchLastEstimateStatisticsOperation', 
               'Get-MgSecurityCaseEdiscoveryCaseSearchNoncustodialSource', 
               'Get-MgSecurityCaseEdiscoveryCaseSearchNoncustodialSourceCount', 
               'Get-MgSecurityCaseEdiscoveryCaseSetting', 
               'Get-MgSecurityCaseEdiscoveryCaseTag', 
               'Get-MgSecurityCaseEdiscoveryCaseTagChildTag', 
               'Get-MgSecurityCaseEdiscoveryCaseTagChildTagCount', 
               'Get-MgSecurityCaseEdiscoveryCaseTagCount', 
               'Get-MgSecurityCaseEdiscoveryCaseTagParent', 
               'Get-MgSecurityIdentity', 'Get-MgSecurityIdentityHealthIssue', 
               'Get-MgSecurityIdentityHealthIssueCount', 'Get-MgSecurityIncident', 
               'Get-MgSecurityIncidentAlert', 
               'Get-MgSecurityIncidentAlertCommentCount', 
               'Get-MgSecurityIncidentAlertCount', 'Get-MgSecurityIncidentCount', 
               'Get-MgSecurityLabel', 'Get-MgSecurityLabelAuthority', 
               'Get-MgSecurityLabelAuthorityCount', 'Get-MgSecurityLabelCategory', 
               'Get-MgSecurityLabelCategoryCount', 
               'Get-MgSecurityLabelCategorySubcategory', 
               'Get-MgSecurityLabelCategorySubcategoryCount', 
               'Get-MgSecurityLabelCitation', 'Get-MgSecurityLabelCitationCount', 
               'Get-MgSecurityLabelDepartment', 
               'Get-MgSecurityLabelDepartmentCount', 
               'Get-MgSecurityLabelFilePlanReference', 
               'Get-MgSecurityLabelFilePlanReferenceCount', 
               'Get-MgSecurityLabelRetentionEventType', 
               'Get-MgSecurityLabelRetentionLabel', 
               'Get-MgSecurityLabelRetentionLabelCount', 
               'Get-MgSecurityLabelRetentionLabelDescriptor', 
               'Get-MgSecurityLabelRetentionLabelDescriptorAuthorityTemplate', 
               'Get-MgSecurityLabelRetentionLabelDescriptorCategoryTemplate', 
               'Get-MgSecurityLabelRetentionLabelDescriptorCitationTemplate', 
               'Get-MgSecurityLabelRetentionLabelDescriptorDepartmentTemplate', 
               'Get-MgSecurityLabelRetentionLabelDescriptorFilePlanReferenceTemplate', 
               'Get-MgSecurityLabelRetentionLabelDispositionReviewStage', 
               'Get-MgSecurityLabelRetentionLabelDispositionReviewStageCount', 
               'Get-MgSecuritySecureScore', 
               'Get-MgSecuritySecureScoreControlProfile', 
               'Get-MgSecuritySecureScoreControlProfileCount', 
               'Get-MgSecuritySecureScoreCount', 
               'Get-MgSecuritySubjectRightsRequest', 
               'Get-MgSecuritySubjectRightsRequestApprover', 
               'Get-MgSecuritySubjectRightsRequestApproverCount', 
               'Get-MgSecuritySubjectRightsRequestApproverMailboxSetting', 
               'Get-MgSecuritySubjectRightsRequestApproverServiceProvisioningError', 
               'Get-MgSecuritySubjectRightsRequestApproverServiceProvisioningErrorCount', 
               'Get-MgSecuritySubjectRightsRequestCollaborator', 
               'Get-MgSecuritySubjectRightsRequestCollaboratorCount', 
               'Get-MgSecuritySubjectRightsRequestCollaboratorMailboxSetting', 
               'Get-MgSecuritySubjectRightsRequestCollaboratorServiceProvisioningError', 
               'Get-MgSecuritySubjectRightsRequestCollaboratorServiceProvisioningErrorCount', 
               'Get-MgSecuritySubjectRightsRequestCount', 
               'Get-MgSecuritySubjectRightsRequestFinalAttachment', 
               'Get-MgSecuritySubjectRightsRequestFinalReport', 
               'Get-MgSecuritySubjectRightsRequestNote', 
               'Get-MgSecuritySubjectRightsRequestNoteCount', 
               'Get-MgSecuritySubjectRightsRequestTeam', 
               'Get-MgSecurityThreatIntelligence', 
               'Get-MgSecurityThreatIntelligenceArticle', 
               'Get-MgSecurityThreatIntelligenceArticleCount', 
               'Get-MgSecurityThreatIntelligenceArticleIndicator', 
               'Get-MgSecurityThreatIntelligenceArticleIndicatorArtifact', 
               'Get-MgSecurityThreatIntelligenceArticleIndicatorCount', 
               'Get-MgSecurityThreatIntelligenceHost', 
               'Get-MgSecurityThreatIntelligenceHostChildHostPair', 
               'Get-MgSecurityThreatIntelligenceHostChildHostPairCount', 
               'Get-MgSecurityThreatIntelligenceHostComponent', 
               'Get-MgSecurityThreatIntelligenceHostComponentCount', 
               'Get-MgSecurityThreatIntelligenceHostComponentHost', 
               'Get-MgSecurityThreatIntelligenceHostCookie', 
               'Get-MgSecurityThreatIntelligenceHostCookieCount', 
               'Get-MgSecurityThreatIntelligenceHostCookieHost', 
               'Get-MgSecurityThreatIntelligenceHostCount', 
               'Get-MgSecurityThreatIntelligenceHostPair', 
               'Get-MgSecurityThreatIntelligenceHostPairChildHost', 
               'Get-MgSecurityThreatIntelligenceHostPairCount', 
               'Get-MgSecurityThreatIntelligenceHostPairParentHost', 
               'Get-MgSecurityThreatIntelligenceHostParentHostPair', 
               'Get-MgSecurityThreatIntelligenceHostParentHostPairCount', 
               'Get-MgSecurityThreatIntelligenceHostPassiveDns', 
               'Get-MgSecurityThreatIntelligenceHostPassiveDnsCount', 
               'Get-MgSecurityThreatIntelligenceHostPassiveDnsReverse', 
               'Get-MgSecurityThreatIntelligenceHostPassiveDnsReverseCount', 
               'Get-MgSecurityThreatIntelligenceHostPort', 
               'Get-MgSecurityThreatIntelligenceHostPortCount', 
               'Get-MgSecurityThreatIntelligenceHostPortHost', 
               'Get-MgSecurityThreatIntelligenceHostPortMostRecentSslCertificate', 
               'Get-MgSecurityThreatIntelligenceHostReputation', 
               'Get-MgSecurityThreatIntelligenceHostSslCertificate', 
               'Get-MgSecurityThreatIntelligenceHostSslCertificateCount', 
               'Get-MgSecurityThreatIntelligenceHostSslCertificateHost', 
               'Get-MgSecurityThreatIntelligenceHostSubdomain', 
               'Get-MgSecurityThreatIntelligenceHostSubdomainCount', 
               'Get-MgSecurityThreatIntelligenceHostTracker', 
               'Get-MgSecurityThreatIntelligenceHostTrackerCount', 
               'Get-MgSecurityThreatIntelligenceHostTrackerHost', 
               'Get-MgSecurityThreatIntelligenceHostWhoi', 
               'Get-MgSecurityThreatIntelligenceIntelProfile', 
               'Get-MgSecurityThreatIntelligenceIntelProfileCount', 
               'Get-MgSecurityThreatIntelligenceIntelProfileIndicator', 
               'Get-MgSecurityThreatIntelligenceIntelProfileIndicatorCount', 
               'Get-MgSecurityThreatIntelligencePassiveDnsRecord', 
               'Get-MgSecurityThreatIntelligencePassiveDnsRecordArtifact', 
               'Get-MgSecurityThreatIntelligencePassiveDnsRecordCount', 
               'Get-MgSecurityThreatIntelligencePassiveDnsRecordParentHost', 
               'Get-MgSecurityThreatIntelligenceProfileIndicator', 
               'Get-MgSecurityThreatIntelligenceProfileIndicatorArtifact', 
               'Get-MgSecurityThreatIntelligenceProfileIndicatorCount', 
               'Get-MgSecurityThreatIntelligenceSslCertificate', 
               'Get-MgSecurityThreatIntelligenceSslCertificateCount', 
               'Get-MgSecurityThreatIntelligenceSslCertificateRelatedHost', 
               'Get-MgSecurityThreatIntelligenceSslCertificateRelatedHostCount', 
               'Get-MgSecurityThreatIntelligenceSubdomain', 
               'Get-MgSecurityThreatIntelligenceSubdomainCount', 
               'Get-MgSecurityThreatIntelligenceSubdomainHost', 
               'Get-MgSecurityThreatIntelligenceVulnerability', 
               'Get-MgSecurityThreatIntelligenceVulnerabilityArticle', 
               'Get-MgSecurityThreatIntelligenceVulnerabilityArticleCount', 
               'Get-MgSecurityThreatIntelligenceVulnerabilityComponent', 
               'Get-MgSecurityThreatIntelligenceVulnerabilityComponentCount', 
               'Get-MgSecurityThreatIntelligenceVulnerabilityCount', 
               'Get-MgSecurityThreatIntelligenceWhoisHistoryRecord', 
               'Get-MgSecurityThreatIntelligenceWhoisHistoryRecordCount', 
               'Get-MgSecurityThreatIntelligenceWhoisHistoryRecordHost', 
               'Get-MgSecurityThreatIntelligenceWhoisRecord', 
               'Get-MgSecurityThreatIntelligenceWhoisRecordCount', 
               'Get-MgSecurityThreatIntelligenceWhoisRecordHistory', 
               'Get-MgSecurityThreatIntelligenceWhoisRecordHistoryCount', 
               'Get-MgSecurityThreatIntelligenceWhoisRecordHost', 
               'Get-MgSecurityTrigger', 'Get-MgSecurityTriggerRetentionEvent', 
               'Get-MgSecurityTriggerRetentionEventCount', 
               'Get-MgSecurityTriggerRetentionEventType', 
               'Get-MgSecurityTriggerType', 
               'Get-MgSecurityTriggerTypeRetentionEventType', 
               'Get-MgSecurityTriggerTypeRetentionEventTypeCount', 
               'Initialize-MgSecurityCaseEdiscoveryCaseCustodian', 
               'Invoke-MgAsSecurityCaseEdiscoveryCaseTagHierarchy', 
               'Invoke-MgCommentSecurityAlert', 
               'Invoke-MgEstimateSecurityCaseEdiscoveryCaseSearchStatistics', 
               'Invoke-MgReopenSecurityCaseEdiscoveryCase', 'New-MgSecurityAlert', 
               'New-MgSecurityAlertV2', 'New-MgSecurityAttackSimulation', 
               'New-MgSecurityAttackSimulationAutomation', 
               'New-MgSecurityAttackSimulationAutomationRun', 
               'New-MgSecurityAttackSimulationEndUserNotification', 
               'New-MgSecurityAttackSimulationEndUserNotificationDetail', 
               'New-MgSecurityAttackSimulationLandingPage', 
               'New-MgSecurityAttackSimulationLandingPageDetail', 
               'New-MgSecurityAttackSimulationLoginPage', 
               'New-MgSecurityAttackSimulationOperation', 
               'New-MgSecurityAttackSimulationPayload', 
               'New-MgSecurityAttackSimulationTraining', 
               'New-MgSecurityAttackSimulationTrainingLanguageDetail', 
               'New-MgSecurityCaseEdiscoveryCase', 
               'New-MgSecurityCaseEdiscoveryCaseCustodian', 
               'New-MgSecurityCaseEdiscoveryCaseCustodianSiteSource', 
               'New-MgSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSource', 
               'New-MgSecurityCaseEdiscoveryCaseCustodianUserSource', 
               'New-MgSecurityCaseEdiscoveryCaseNoncustodialDataSource', 
               'New-MgSecurityCaseEdiscoveryCaseOperation', 
               'New-MgSecurityCaseEdiscoveryCaseReviewSet', 
               'New-MgSecurityCaseEdiscoveryCaseReviewSetQuery', 
               'New-MgSecurityCaseEdiscoveryCaseSearch', 
               'New-MgSecurityCaseEdiscoveryCaseSearchAdditionalSource', 
               'New-MgSecurityCaseEdiscoveryCaseTag', 
               'New-MgSecurityIdentityHealthIssue', 'New-MgSecurityIncident', 
               'New-MgSecurityLabelAuthority', 'New-MgSecurityLabelCategory', 
               'New-MgSecurityLabelCategorySubcategory', 
               'New-MgSecurityLabelCitation', 'New-MgSecurityLabelDepartment', 
               'New-MgSecurityLabelFilePlanReference', 
               'New-MgSecurityLabelRetentionLabel', 
               'New-MgSecurityLabelRetentionLabelDispositionReviewStage', 
               'New-MgSecuritySecureScore', 
               'New-MgSecuritySecureScoreControlProfile', 
               'New-MgSecuritySubjectRightsRequest', 
               'New-MgSecuritySubjectRightsRequestNote', 
               'New-MgSecurityThreatIntelligenceArticle', 
               'New-MgSecurityThreatIntelligenceArticleIndicator', 
               'New-MgSecurityThreatIntelligenceHost', 
               'New-MgSecurityThreatIntelligenceHostComponent', 
               'New-MgSecurityThreatIntelligenceHostCookie', 
               'New-MgSecurityThreatIntelligenceHostPair', 
               'New-MgSecurityThreatIntelligenceHostPort', 
               'New-MgSecurityThreatIntelligenceHostSslCertificate', 
               'New-MgSecurityThreatIntelligenceHostTracker', 
               'New-MgSecurityThreatIntelligenceIntelProfile', 
               'New-MgSecurityThreatIntelligencePassiveDnsRecord', 
               'New-MgSecurityThreatIntelligenceProfileIndicator', 
               'New-MgSecurityThreatIntelligenceSslCertificate', 
               'New-MgSecurityThreatIntelligenceSubdomain', 
               'New-MgSecurityThreatIntelligenceVulnerability', 
               'New-MgSecurityThreatIntelligenceVulnerabilityComponent', 
               'New-MgSecurityThreatIntelligenceWhoisHistoryRecord', 
               'New-MgSecurityThreatIntelligenceWhoisRecord', 
               'New-MgSecurityTriggerRetentionEvent', 
               'New-MgSecurityTriggerTypeRetentionEventType', 
               'Publish-MgSecurityCaseEdiscoveryCaseCustodian', 
               'Publish-MgSecurityCaseEdiscoveryCaseNoncustodialDataSource', 
               'Remove-MgSecurityAlertV2', 'Remove-MgSecurityAttackSimulation', 
               'Remove-MgSecurityAttackSimulationAutomation', 
               'Remove-MgSecurityAttackSimulationAutomationRun', 
               'Remove-MgSecurityAttackSimulationEndUserNotification', 
               'Remove-MgSecurityAttackSimulationEndUserNotificationDetail', 
               'Remove-MgSecurityAttackSimulationLandingPage', 
               'Remove-MgSecurityAttackSimulationLandingPageDetail', 
               'Remove-MgSecurityAttackSimulationLoginPage', 
               'Remove-MgSecurityAttackSimulationOperation', 
               'Remove-MgSecurityAttackSimulationPayload', 
               'Remove-MgSecurityAttackSimulationTraining', 
               'Remove-MgSecurityAttackSimulationTrainingLanguageDetail', 
               'Remove-MgSecurityCase', 'Remove-MgSecurityCaseEdiscoveryCase', 
               'Remove-MgSecurityCaseEdiscoveryCaseCustodian', 
               'Remove-MgSecurityCaseEdiscoveryCaseCustodianHold', 
               'Remove-MgSecurityCaseEdiscoveryCaseCustodianSiteSource', 
               'Remove-MgSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSource', 
               'Remove-MgSecurityCaseEdiscoveryCaseCustodianUserSource', 
               'Remove-MgSecurityCaseEdiscoveryCaseNoncustodialDataSource', 
               'Remove-MgSecurityCaseEdiscoveryCaseNoncustodialDataSourceHold', 
               'Remove-MgSecurityCaseEdiscoveryCaseOperation', 
               'Remove-MgSecurityCaseEdiscoveryCaseReviewSet', 
               'Remove-MgSecurityCaseEdiscoveryCaseReviewSetQuery', 
               'Remove-MgSecurityCaseEdiscoveryCaseSearch', 
               'Remove-MgSecurityCaseEdiscoveryCaseSearchAdditionalSource', 
               'Remove-MgSecurityCaseEdiscoveryCaseSetting', 
               'Remove-MgSecurityCaseEdiscoveryCaseTag', 
               'Remove-MgSecurityIdentity', 'Remove-MgSecurityIdentityHealthIssue', 
               'Remove-MgSecurityIncident', 'Remove-MgSecurityLabel', 
               'Remove-MgSecurityLabelAuthority', 'Remove-MgSecurityLabelCategory', 
               'Remove-MgSecurityLabelCategorySubcategory', 
               'Remove-MgSecurityLabelCitation', 
               'Remove-MgSecurityLabelDepartment', 
               'Remove-MgSecurityLabelFilePlanReference', 
               'Remove-MgSecurityLabelRetentionLabel', 
               'Remove-MgSecurityLabelRetentionLabelDescriptor', 
               'Remove-MgSecurityLabelRetentionLabelDispositionReviewStage', 
               'Remove-MgSecuritySecureScore', 
               'Remove-MgSecuritySecureScoreControlProfile', 
               'Remove-MgSecuritySubjectRightsRequest', 
               'Remove-MgSecuritySubjectRightsRequestNote', 
               'Remove-MgSecurityThreatIntelligence', 
               'Remove-MgSecurityThreatIntelligenceArticle', 
               'Remove-MgSecurityThreatIntelligenceArticleIndicator', 
               'Remove-MgSecurityThreatIntelligenceHost', 
               'Remove-MgSecurityThreatIntelligenceHostComponent', 
               'Remove-MgSecurityThreatIntelligenceHostCookie', 
               'Remove-MgSecurityThreatIntelligenceHostPair', 
               'Remove-MgSecurityThreatIntelligenceHostPort', 
               'Remove-MgSecurityThreatIntelligenceHostReputation', 
               'Remove-MgSecurityThreatIntelligenceHostSslCertificate', 
               'Remove-MgSecurityThreatIntelligenceHostTracker', 
               'Remove-MgSecurityThreatIntelligenceIntelProfile', 
               'Remove-MgSecurityThreatIntelligencePassiveDnsRecord', 
               'Remove-MgSecurityThreatIntelligenceProfileIndicator', 
               'Remove-MgSecurityThreatIntelligenceSslCertificate', 
               'Remove-MgSecurityThreatIntelligenceSubdomain', 
               'Remove-MgSecurityThreatIntelligenceVulnerability', 
               'Remove-MgSecurityThreatIntelligenceVulnerabilityComponent', 
               'Remove-MgSecurityThreatIntelligenceWhoisHistoryRecord', 
               'Remove-MgSecurityThreatIntelligenceWhoisRecord', 
               'Remove-MgSecurityTrigger', 
               'Remove-MgSecurityTriggerRetentionEvent', 
               'Remove-MgSecurityTriggerType', 
               'Remove-MgSecurityTriggerTypeRetentionEventType', 
               'Reset-MgSecurityCaseEdiscoveryCaseSettingToDefault', 
               'Set-MgSecurityAlert', 'Set-MgSecurityIncidentAlertComment', 
               'Start-MgSecurityHuntingQuery', 'Update-MgSecurityAlert', 
               'Update-MgSecurityAlertV2', 
               'Update-MgSecurityAttackSimulationAutomation', 
               'Update-MgSecurityAttackSimulationAutomationRun', 
               'Update-MgSecurityAttackSimulationEndUserNotification', 
               'Update-MgSecurityAttackSimulationEndUserNotificationDetail', 
               'Update-MgSecurityAttackSimulationLandingPage', 
               'Update-MgSecurityAttackSimulationLandingPageDetail', 
               'Update-MgSecurityAttackSimulationLoginPage', 
               'Update-MgSecurityAttackSimulationOperation', 
               'Update-MgSecurityAttackSimulationPayload', 
               'Update-MgSecurityAttackSimulationTraining', 
               'Update-MgSecurityAttackSimulationTrainingLanguageDetail', 
               'Update-MgSecurityCase', 'Update-MgSecurityCaseEdiscoveryCase', 
               'Update-MgSecurityCaseEdiscoveryCaseCustodian', 
               'Update-MgSecurityCaseEdiscoveryCaseCustodianIndex', 
               'Update-MgSecurityCaseEdiscoveryCaseCustodianSiteSource', 
               'Update-MgSecurityCaseEdiscoveryCaseCustodianUnifiedGroupSource', 
               'Update-MgSecurityCaseEdiscoveryCaseCustodianUserSource', 
               'Update-MgSecurityCaseEdiscoveryCaseNoncustodialDataSource', 
               'Update-MgSecurityCaseEdiscoveryCaseNoncustodialDataSourceIndex', 
               'Update-MgSecurityCaseEdiscoveryCaseOperation', 
               'Update-MgSecurityCaseEdiscoveryCaseReviewSet', 
               'Update-MgSecurityCaseEdiscoveryCaseReviewSetQuery', 
               'Update-MgSecurityCaseEdiscoveryCaseSearch', 
               'Update-MgSecurityCaseEdiscoveryCaseSearchAdditionalSource', 
               'Update-MgSecurityCaseEdiscoveryCaseSetting', 
               'Update-MgSecurityCaseEdiscoveryCaseTag', 
               'Update-MgSecurityIdentity', 'Update-MgSecurityIdentityHealthIssue', 
               'Update-MgSecurityIncident', 'Update-MgSecurityLabel', 
               'Update-MgSecurityLabelAuthority', 'Update-MgSecurityLabelCategory', 
               'Update-MgSecurityLabelCategorySubcategory', 
               'Update-MgSecurityLabelCitation', 
               'Update-MgSecurityLabelDepartment', 
               'Update-MgSecurityLabelFilePlanReference', 
               'Update-MgSecurityLabelRetentionLabel', 
               'Update-MgSecurityLabelRetentionLabelDescriptor', 
               'Update-MgSecurityLabelRetentionLabelDispositionReviewStage', 
               'Update-MgSecuritySecureScore', 
               'Update-MgSecuritySecureScoreControlProfile', 
               'Update-MgSecuritySubjectRightsRequest', 
               'Update-MgSecuritySubjectRightsRequestApproverMailboxSetting', 
               'Update-MgSecuritySubjectRightsRequestCollaboratorMailboxSetting', 
               'Update-MgSecuritySubjectRightsRequestNote', 
               'Update-MgSecurityThreatIntelligence', 
               'Update-MgSecurityThreatIntelligenceArticle', 
               'Update-MgSecurityThreatIntelligenceArticleIndicator', 
               'Update-MgSecurityThreatIntelligenceHost', 
               'Update-MgSecurityThreatIntelligenceHostComponent', 
               'Update-MgSecurityThreatIntelligenceHostCookie', 
               'Update-MgSecurityThreatIntelligenceHostPair', 
               'Update-MgSecurityThreatIntelligenceHostPort', 
               'Update-MgSecurityThreatIntelligenceHostReputation', 
               'Update-MgSecurityThreatIntelligenceHostSslCertificate', 
               'Update-MgSecurityThreatIntelligenceHostTracker', 
               'Update-MgSecurityThreatIntelligenceIntelProfile', 
               'Update-MgSecurityThreatIntelligencePassiveDnsRecord', 
               'Update-MgSecurityThreatIntelligenceProfileIndicator', 
               'Update-MgSecurityThreatIntelligenceSslCertificate', 
               'Update-MgSecurityThreatIntelligenceSubdomain', 
               'Update-MgSecurityThreatIntelligenceVulnerability', 
               'Update-MgSecurityThreatIntelligenceVulnerabilityComponent', 
               'Update-MgSecurityThreatIntelligenceWhoisHistoryRecord', 
               'Update-MgSecurityThreatIntelligenceWhoisRecord', 
               'Update-MgSecurityTrigger', 
               'Update-MgSecurityTriggerRetentionEvent', 
               'Update-MgSecurityTriggerType', 
               'Update-MgSecurityTriggerTypeRetentionEventType'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoRgYJKoZIhvcNAQcCoIIoNzCCKDMCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCFuxPaU28nTinu
# JwwUiPGJh21ZiyMGvu8Mk1Hoz/hCTaCCDXYwggX0MIID3KADAgECAhMzAAAEBGx0
# Bv9XKydyAAAAAAQEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTE0WhcNMjUwOTExMjAxMTE0WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQC0KDfaY50MDqsEGdlIzDHBd6CqIMRQWW9Af1LHDDTuFjfDsvna0nEuDSYJmNyz
# NB10jpbg0lhvkT1AzfX2TLITSXwS8D+mBzGCWMM/wTpciWBV/pbjSazbzoKvRrNo
# DV/u9omOM2Eawyo5JJJdNkM2d8qzkQ0bRuRd4HarmGunSouyb9NY7egWN5E5lUc3
# a2AROzAdHdYpObpCOdeAY2P5XqtJkk79aROpzw16wCjdSn8qMzCBzR7rvH2WVkvF
# HLIxZQET1yhPb6lRmpgBQNnzidHV2Ocxjc8wNiIDzgbDkmlx54QPfw7RwQi8p1fy
# 4byhBrTjv568x8NGv3gwb0RbAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU8huhNbETDU+ZWllL4DNMPCijEU4w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMjkyMzAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAIjmD9IpQVvfB1QehvpC
# Ge7QeTQkKQ7j3bmDMjwSqFL4ri6ae9IFTdpywn5smmtSIyKYDn3/nHtaEn0X1NBj
# L5oP0BjAy1sqxD+uy35B+V8wv5GrxhMDJP8l2QjLtH/UglSTIhLqyt8bUAqVfyfp
# h4COMRvwwjTvChtCnUXXACuCXYHWalOoc0OU2oGN+mPJIJJxaNQc1sjBsMbGIWv3
# cmgSHkCEmrMv7yaidpePt6V+yPMik+eXw3IfZ5eNOiNgL1rZzgSJfTnvUqiaEQ0X
# dG1HbkDv9fv6CTq6m4Ty3IzLiwGSXYxRIXTxT4TYs5VxHy2uFjFXWVSL0J2ARTYL
# E4Oyl1wXDF1PX4bxg1yDMfKPHcE1Ijic5lx1KdK1SkaEJdto4hd++05J9Bf9TAmi
# u6EK6C9Oe5vRadroJCK26uCUI4zIjL/qG7mswW+qT0CW0gnR9JHkXCWNbo8ccMk1
# sJatmRoSAifbgzaYbUz8+lv+IXy5GFuAmLnNbGjacB3IMGpa+lbFgih57/fIhamq
# 5VhxgaEmn/UjWyr+cPiAFWuTVIpfsOjbEAww75wURNM1Imp9NJKye1O24EspEHmb
# DmqCUcq7NqkOKIG4PVm3hDDED/WQpzJDkvu4FrIbvyTGVU01vKsg4UfcdiZ0fQ+/
# V0hf8yrtq9CkB8iIuk5bBxuPMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGiYwghoiAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAQEbHQG/1crJ3IAAAAABAQwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIBuvdTPs468xt0elgyXkpnrQ
# 259+/taq/W2v/tj8kaffMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEArTkeCjeaauuZGNF5okcuonKr9Gd8emJvqh381KLvObtbpb/ZukUUMRao
# HSm0ref2ZqcyZEScjAWsDq5ysLPrxPacoTrHYi2pWWb7/35o0gM3uhlX2DzWeR2P
# rmdR60EWkh7ifxKEB6RbXo8a2DIGuUO866IJXh6IUaFPbVMnDAX8QJOvJx5H0kpS
# gWf97/Z/CZHs+PBVQ5s1D/fKHL3JOlyqa5JLYHIAVpp9yRkfR/qgXWMcSZsQSvjo
# lQAn8k2+NeEIib5wjB3lUFyUgHUOkkUo0QRyotM800Ey/pQ5o4Tqc8SITENi/CY+
# cxFVb6/UUvP6nwP8lheA+1eSc6ZGpaGCF7AwghesBgorBgEEAYI3AwMBMYIXnDCC
# F5gGCSqGSIb3DQEHAqCCF4kwgheFAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFaBgsq
# hkiG9w0BCRABBKCCAUkEggFFMIIBQQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCAleV9KI+6ZG4x87HkVTOPzxsBA0A9yCeGiHkGA6mlQjAIGZzu+37p+
# GBMyMDI0MTEyMDE2NTg1Mi4zMDNaMASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# TjozNjA1LTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaCCEf4wggcoMIIFEKADAgECAhMzAAAB91ggdQTK+8L0AAEAAAH3MA0G
# CSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTI0
# MDcyNTE4MzEwNloXDTI1MTAyMjE4MzEwNlowgdMxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9w
# ZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjM2MDUt
# MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0OdHTBNom6/uXKaEKP9r
# PITkT6QxF11tjzB0Nk1byDpPrFTHha3hxwSdTcr8Y0a3k6EQlwqy6ROz42e0R5eD
# W+dCoQapipDIFUOYp3oNuqwX/xepATEkY17MyXFx6rQW2NcWUJW3Qo2AuJ0HOtbl
# SpItQZPGmHnGqkt/DB45Fwxk6VoSvxNcQKhKETkuzrt8U6DRccQm1FdhmPKgDzgc
# fDPM5o+GnzbiMu6y069A4EHmLMmkecSkVvBmcZ8VnzFHTDkGLdpnDV5FXjVObAgb
# SM0cnqYSGfRp7VGHBRqyoscvR4bcQ+CV9pDjbJ6S5rZn1uA8hRhj09Hs33HRevt4
# oWAVYGItgEsG+BrCYbpgWMDEIVnAgPZEiPAaI8wBGemE4feEkuz7TAwgkRBcUzLg
# Q4uvPqRD1A+Jkt26+pDqWYSn0MA8j0zacQk9q/AvciPXD9It2ez+mqEzgFRRsJGL
# tcf9HksvK8Jsd6I5zFShlqi5bpzf1Y4NOiNOh5QwW1pIvA5irlal7qFhkAeeeZqm
# op8+uNxZXxFCQG3R3s5pXW89FiCh9rmXrVqOCwgcXFIJQAQkllKsI+UJqGq9rmRA
# BJz5lHKTFYmFwcM52KWWjNx3z6odwz2h+sxaxewToe9GqtDx3/aU+yqNRcB8w0tS
# XUf+ylN4uk5xHEpLpx+ZNNsCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBTfRqQzP3m9
# PZWuLf1p8/meFfkmmDAfBgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
# BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmww
# bAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0El
# MjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUF
# BwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEAN0ajafILeL6S
# QIMIMAXM1Qd6xaoci2mOrpR8vKWyyTsL3b83A7XGLiAbQxTrqnXvVWWeNst5YQD8
# saO+UTgOLJdTdfUADhLXoK+RlwjfndimIJT9MH9tUYXLzJXKhZM09ouPwNsrn8YO
# LIpdAi5TPyN8Cl11OGZSlP9r8JnvomW00AoJ4Pl9rlg0G5lcQknAXqHa9nQdWp1Z
# xXqNd+0JsKmlR8tcANX33ClM9NnaClJExLQHiKeHUUWtqyLMl65TW6wRM7XlF7Y+
# PTnC8duNWn4uLng+ON/Z39GO6qBj7IEZxoq4o3avEh9ba43UU6TgzVZaBm8VaA0w
# SwUe/pqpTOYFWN62XL3gl/JC2pzfIPxP66XfRLIxafjBVXm8KVDn2cML9IvRK02s
# 941Y5+RR4gSAOhLiQQ6A03VNRup+spMa0k+XTPAi+2aMH5xa1Zjb/K8u9f9M05U0
# /bUMJXJDP++ysWpJbVRDiHG7szaca+r3HiUPjQJyQl2NiOcYTGV/DcLrLCBK2zG5
# 03FGb04N5Kf10XgAwFaXlod5B9eKh95PnXKx2LNBgLwG85anlhhGxxBQ5mFsJGkB
# n0PZPtAzZyfr96qxzpp2pH9DJJcjKCDrMmZziXazpa5VVN36CO1kDU4ABkSYTXOM
# 8RmJXuQm7mUF3bWmj+hjAJb4pz6hT5UwggdxMIIFWaADAgECAhMzAAAAFcXna54C
# m0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UE
# CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZp
# Y2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAxODMy
# MjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0B
# AQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51
# yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY
# 6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9
# cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130/o5Tz9bshVZN
# 7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDua
# Rr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGpF1tnYN74
# kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2
# K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNOwTM5
# TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
# i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
# BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3Pmri
# Lq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUC
# BBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJl
# pxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIB
# FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9y
# eS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUA
# YgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
# 1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2Ny
# bC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0XzIw
# MTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
# Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/yp
# b+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulm
# ZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM
# 9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECW
# OKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2FzLixre24/LAl4
# FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3Uw
# xTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFXSVRk2XPX
# fx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVX
# VAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/AsGC
# onsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
# 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
# ahC0HVUzWLOhcGbyoYIDWTCCAkECAQEwggEBoYHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# TjozNjA1LTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaIjCgEBMAcGBSsOAwIaAxUAb28KDG/xXbNBjmM7/nqw3bgrEOaggYMw
# gYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsF
# AAIFAOroN38wIhgPMjAyNDExMjAxMDI1MDNaGA8yMDI0MTEyMTEwMjUwM1owdzA9
# BgorBgEEAYRZCgQBMS8wLTAKAgUA6ug3fwIBADAKAgEAAgIcwgIB/zAHAgEAAgIS
# 8zAKAgUA6umI/wIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAow
# CAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQCNNna1oXoq
# A6Z3AVwlFcRAslfeu/rJDsJ2Yw7mdLHUQZowu4REvuk7ybCc9BdXZL6NhxFM752C
# yuS8tEzAJ2oRxRlk4667J8AtMd8784omcvNvNXxZOAe/HB14iNGSCnq/EM+vnd82
# 0pxTnhF1KVyi9WjsxOESN0xkV5gr5vesF4trEzs3Lcz6DqMGaGXFkQBsvPrTTk6c
# +upzbL72qMjCLnzCRXk8sfE7mkhXGl6Mp/5MlAOPZY9pPomeSigDsYlx0BADPsFx
# rYm4gnPb2970lb266L2VvrR8Ox+oO9ptuiYVurl9gIhz5kx80tiL15cwCulotaCy
# dIZ28EKBZ6bgMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
# IDIwMTACEzMAAAH3WCB1BMr7wvQAAQAAAfcwDQYJYIZIAWUDBAIBBQCgggFKMBoG
# CSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgQzRP58dO
# x3HRDtRXNteqH8QPNc7n9aRf2lw14B+kinowgfoGCyqGSIb3DQEJEAIvMYHqMIHn
# MIHkMIG9BCAh2pjaa3ca0ecYuhu60uYHP/IKnPbedbVQJ5SoIH5Z4jCBmDCBgKR+
# MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
# ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMT
# HU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB91ggdQTK+8L0AAEA
# AAH3MCIEIJa3To5fV97jyzuuChXO0+On8FzVLG0tIEHt5FgpiztjMA0GCSqGSIb3
# DQEBCwUABIICALpJ58/qoR0YvEKW0aNn2/F/yAgXx01lzxJk6DxWqXnj0ZhV9ea4
# dvy/n2TxgBl45aoFPRc094amSt4d7H/otuWPyKGMjVHAw7uSBQr+XlYtl2d4R9+9
# pdDCqzt8Nceod+m3CjTJfvRYSvpgzEDTL4O3u65M6qy5Fpd6aFHk3teoMZ2/jR5z
# ypxAnXlm1Ra03riE5cKkk0+6hAJGLEoQkQvfbLmTlhCPFtS9zQAbLAPekYy+rma+
# 0PwQfuJYZVUOCvXtzqngljgs7yUaHjjFoAs3Ee9CTnvfX687T0p6PiII/+oHyxcB
# XMtYNdlG5CF4zgIClNpIjks0aWWkW6hjfPPToApa/Pm0ATrw4BSWyj5Ak7UapNNY
# qCTnF7nMHPqmltiVUd8++SeFkmms4jTULlSf3vr9dS9N5dCfdzNArlMDTOdQRSok
# S19mJy1k3O/pddqK3kgEGKl7m7oEOzWUHFH6r7B9/XaP18LI1d3mCzGMmbEQatN1
# JSEDwSxptnDYGCiges8Hsly2ejDZPI+ahR2hbDemRG7yW1++1wtmOumfTxuZXx2t
# a3zVp0joVi2lZwmgWL8n6jeEydaNLievDbkHW8lhNKItG7bILv8bzjs4DtSmlp2g
# nwfRz4eluhEL51X3XRcylFemXzntBgrt1FKa+CyQmYaEy1NE1ybOt4Qg
# SIG # End signature block
